### ISSUE TITLE
WrappingWidth Not Work in those languages not use whitespace as word separator 

### ISSUE THREAD

**Issue by personball** [SixLabors/Fonts#103]
At https://github.com/SixLabors/Fonts/blob/master/src/SixLabors.Fonts/TextLayout.cs#L114

```
if (options.WrappingWidth > 0 && char.IsWhiteSpace(text[i]))
{
    ...
}
```

Languages like **Chinese**, do not use **WhiteSpace** as word separator.

Is there any plan to support this?

**Comment by tocsoft** [comment]
We would love to support this we need to update our layout engine based on the details in the [unicode line breaking algorithm](http://unicode.org/reports/tr14/)

we can't promise anything with regarding timelines on making these improvements and would gladly accept pull requests with the required fixes.
