### ISSUE TITLE
Clarify difference between TextMeasurer.Measure() and TextMeasurer.MeasureBounds()

### ISSUE THREAD

**Issue by mogikanin** [SixLabors/Fonts#105]
Could someone clarify exact difference between these two methods? Documentation says they both ```Measures the text.```,  but in fact they return different result for same text.

**Comment by mogikanin** [comment]
This is not answer. They return different result for same text, i.e. width\height from Rectangle doesn't equal to width\height from Size.

**Comment by mogikanin** [comment]
The question was not about return type, but about different result. Could you read questions more closely in future?

**Comment by mogikanin** [comment]
@JimBobSquarePants please re-open issue, or explain why width\height is different.

**Comment by JimBobSquarePants** [comment]
> The question was not about return type, but about different result. Could you read questions more closely in future?

Question on Gitter Channel please. Our issues template clearly says so. Don't be rude.
