### ISSUE TITLE
Some fonts are displayed without a top gap with default line height

### ISSUE THREAD

**Issue by sv40** [SixLabors/Fonts#107]
We'd like to draw identical images both in the browser and in a file using ImageSharp.

For example:
When we use font name: 'Arial', font size: 170pt, a browser renders a text with 2 gaps on the top and on the bottom (dot lines are the borders):
![image](https://user-images.githubusercontent.com/22441115/53394426-d66e1f00-39d1-11e9-9565-e8d1dcee873a.png)
https://next.plnkr.co/edit/aQjfQkA7VEBEUHI2?preview

However, using the ImageSharp library, we get a text with pretty small gaps on the top (red lines are the borders):
![image](https://user-images.githubusercontent.com/22441115/53394539-31a01180-39d2-11e9-8873-3e1699ba5aa5.png).

It looks like ImageSharp has different default line height.

Can anyone suggest how to achieve the same behavior for ImageSharp, so that it works exactly just like in a web-browser? Can we adjust the line height in options or do something else?

**Comment by jtheisen** [comment]
I think the real question here is where the additional gap between lines should be added: Above the ascender, below the descender, or both in parts.

The line height appears to be correct as font.Ascender - font.Descender + font.LineGap != font.LineHeight holds. It's just aligning with the ascender line without the mystery gap that browsers add there.
