### ISSUE TITLE
I fond an issue about Chinese character

### ISSUE THREAD

**Issue by haue** [SixLabors/Fonts#112]
example code:
```
var txt = "测试，。？";
```

output is incorrect:
![test1.jpg](https://i.loli.net/2019/08/12/GKVir9RNHvgdjqM.jpg)

see the picture above,

**Comment by willhuo** [comment]
How your code works now?

**Comment by Xeltica** [comment]
Have a same issue. Some multibyte symbols (e.g. `！`) and chinese-characters (also used for Japanese) will be rendered as other characters. It looks like a encoding issue... :thinking:

In my research, I found that some characters were misaligned on the character code.

<details>
<summary>Maps of expected and actually rendered characters</summary>

|expected character|actually-rendered character|
|-|-|
|！|＃|
|”|”|
|＃|＄|
|＄|％|
|％|＆|
|＆|（|
|’|’|
|（|）|
|）|＊|
|１|２|
|２|３|
|３|４|
|４|５|
|５|６|
|６|７|
|７|８|
|８|９|
|９|：|
|０|１|
|、|、|
|。|。|
|，|ー|
|・|・|
|＿|unknown(looks like upper-aligned small dot)|
|＠|Ａ|
|｛|｜|
|｝|〜|
|「|「|
|」|」|
|；|＜|
|：|；|
|＜|＝|
|＞|？|
|？|＠|
|Ａ|Ｂ|
|Ｂ|Ｃ|
|Ｃ|Ｄ|
|Ｄ|Ｅ|
|Ｅ|Ｆ|
|Ｆ|Ｇ|
|Ｇ|Ｈ|
|Ｈ|Ｉ|
|Ｉ|Ｊ|
|Ｊ|Ｋ|
|Ｋ|Ｌ|
|Ｌ|Ｍ|
|Ｍ|Ｎ|
|Ｎ|Ｏ|
|Ｏ|Ｐ|
|Ｐ|Ｑ|
|Ｑ|Ｒ|
|Ｒ|Ｓ|
|Ｓ|Ｔ|
|Ｔ|Ｕ|
|Ｕ|Ｖ|
|Ｖ|Ｗ|
|Ｗ|Ｘ|
|Ｘ|Ｙ|
|Ｙ|Ｚ|
|Ｚ|［|
|魔|魘|

</details>

**Comment by JimBobSquarePants** [comment]
Hi @Xeltica thanks for your additional research!

However, SixLabors.ImageSharp.Drawing 1.0.0-beta0007 is over 1 1/2 years out of date. The latest version is [1.0.0-beta11](https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing/1.0.0-beta11).

Could you please run your tests again with that version and, if there is still an issue, let us know with additional triaging details. 

We'd really appreciate a concise code sample against which we can test the feature. Please include any font details.

Thanks!

**Comment by Xeltica** [comment]
@JimBobSquarePants Thank you for your reply.

I upgraded the version and test it again, then the above problem has been fixed!

**Comment by JimBobSquarePants** [comment]
Excellent! I’ll close this off then. Thanks for testing!
