### ISSUE TITLE
I hope to support the text stroke function

### ISSUE THREAD

**Issue by defoliations** [SixLabors/Fonts#115]
I looked at the related method and found no text stroke method.

**Comment by tocsoft** [comment]
Font doesn't support stroke internally as its just the vector extraction and layout library, stroke support is an product of rendering which happens in `SixLabors.ImageSharp.Drawing` where you pass a `Pen` for the outline/stroke and a `Brush` for the fill its will be covered by one of the `DrawText` methods

**Comment by tocsoft** [comment]
[DrawText extension methods](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.DrawTextExtensions.html#SixLabors_ImageSharp_Processing_DrawTextExtensions_DrawText__1_SixLabors_ImageSharp_Processing_IImageProcessingContext___0__SixLabors_ImageSharp_Processing_TextGraphicsOptions_System_String_Font_SixLabors_ImageSharp_Processing_IBrush___0__SixLabors_ImageSharp_Processing_IPen___0__PointF_) is an example call sit which supports outlining and filling the text while drawing, there are a variety of overloads for different combinations of the 2
