### ISSUE TITLE
fallback fonts for when glyph is not found

### ISSUE THREAD

**Issue by tdesmet** [SixLabors/Fonts#117]
I have a use case where I need to draw text in an image. This text is user input and can be a whole range of languages, It can even be a mix of 2 languages. For example english and chinese.

It would be nice that we can list fallback font's so that if a glyph for a unicode character is not found then it tries in the next provided font until it finds the glyph or there are no more fonts.

**Comment by feliwir** [comment]
Would have a need for this aswell

**Comment by Tylertron1998** [comment]
+1 from me, would really be nice to have this.
