### ISSUE TITLE
SystemFonts Families are empty and cannot add font to empty family

### ISSUE THREAD

**Issue by olivercortinas** [SixLabors/Fonts#118]
I am using OxyPlot.ImageSharp to export oxyplot model content to stream for Xamarin.Forms:
[https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.ImageSharp/PngRenderingContext.cs](url)
This use SixLabors.Font library and i didn't have any problem with UWP and iOS platforms but when i test it on Android the SystemFonts.Families is empty, not sure why this is empty if that error is not happening with the other platforms.
I try to add a font library but when try to do the install nothing happen and the fontFamily is still empty, this is my code:
`
FontFamily family;
            try
            {
                if (!SystemFonts.Families.Any())
                {
                    FontCollection fonts = new FontCollection();
                    family = fonts.Install("DancingScript-VariableFont_wght.ttf");
                }
                else
                {
                    family = SystemFonts.Find(fontFamily);
                }
            }
`
I have the ttf font class on the same folder of this class method.

**Comment by tocsoft** [comment]
This is the list of folders we will look in for ttf files to populate `SystemFonts`
https://github.com/SixLabors/Fonts/blob/122bb271355a71d8cdb656071b438695c3e16377/src/SixLabors.Fonts/SystemFontCollection.cs#L20-L36

unless the devices fonts are located in one of those folders then `SystemFonts` wont find them and thus will be empty. I Presume android must be storing its standard fonts someplace else. (PRs welcome for issues like this as none of the team here are mobile devs.)

With regards installing a local font we just open the file from the path you provide and process it, I presume that the font isn't at the path your passing in... you will want to check the exception being thrown by the call to `Install` that'll help you on that side.

**Comment by olivercortinas** [comment]
As i mentioned before the file is in the same folder that the class:
`FontCollection fonts = new FontCollection();
                    family = fonts.Install("/DancingScript-VariableFont_wght.ttf");`
and get this error:

> System.IO.FileNotFoundException: 'Could not find file /DancingScript-VariableFont_wght.ttf'

If i ran this code line: `string filePath = Path.GetFullPath("DancingScript-VariableFont_wght.ttf");`
returns the same path i set on the install method.

**Comment by tocsoft** [comment]
there looks like there is something fishy about those android streams not implementing the class correctly... not exactly sure but you should be able to copy the asset to a MemoryStream before passing it into fonts as a workaround.

**Comment by olivercortinas** [comment]
**SOLVED:**
The font I add on a folder (Exporters) on the main project (Charts) need to change the Build Action to Embedded resource.
Then i use this code:
`                    Stream stream = this.GetType().Assembly.GetManifestResourceStream("Charts.Exporters.DancingScript-VariableFont_wght.ttf");
                    FontCollection fonts = new FontCollection();
                    family = fonts.Install(stream);
`
That works perfect!!!!
In case someone need to validate the name of the resource could be observed using this line of code:
`var results = this.GetType().Assembly.GetManifestResourceNames();`
Thanks for the responses.
