### ISSUE TITLE
Cant get largest width and/or height for given font

### ISSUE THREAD

**Issue by BreyerW** [SixLabors/Fonts#119]
Use case: font atlas with power of two bitmap size and fixed cell size for ALL characters that is built lazily. 

Currently its possible to use atlas font built lazily with VARYING cell size but thats not what im interested in. The only way to achieve this currently is to rebuild ENTIRE atlas when you encounter bigger char

There are several ways to solve that: let us pull in ALL supported characters by given font (e.g. `IEnumerable<char> font.GetSupportedCharacters()` IEnumerable as memory consumption optimization for large fonts like Asian languages) then we can use `TryMeasureCharacterBounds` with`MemoryMarshal.CreateSpan`

Another way: indirectly expose tables e.g `GetTable` that returns byte array and it will be power user responsibility to interpret correctly given data. Not ideal but this way you minimise the inability to change tables in future

Simplest for end user but i dont know how hard on your end: just expose maxWidth and maxHeight variants on `Font` itself or `FontInstance`

**Comment by JimBobSquarePants** [comment]
`FontMetrics` now exposes `AdvanceWidthMax` and `AdvanceMaxHeight`. That should do what you need.

**Comment by BreyerW** [comment]
@JimBobSquarePants ohh thanks a bunch! :)
