### ISSUE TITLE
add support for glyphs stored in CFF formats

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#12]
if the otf file contains only CFF data then we need to be able to extract the glyphs

http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5176.CFF.pdf

**Comment by personball** [comment]
Is this **Precondition** for support **Open Type Font** ？

**Comment by tzachshabtay** [comment]
Here's an example of a very popular font (font awesome) that currently can't be read by your library (I think it's because it's CFF):
[Font Awesome 5 Free-Solid-900.otf.zip](https://github.com/SixLabors/Fonts/files/4834790/Font.Awesome.5.Free-Solid-900.otf.zip)

**Comment by JimBobSquarePants** [comment]
I'm gonna have a crack at this next.

**Comment by brianpopow** [comment]
@JimBobSquarePants I think we missed to update the readme. We can now remove the `Limitations` section and add CFF glyph's to the feature list
