### ISSUE TITLE
How does output of TextMeasurer.Measure() relate to bounding box?

### ISSUE THREAD

**Issue by okaniku** [SixLabors/Fonts#125]
I'm trying to use ImageSharp to create a texture atlas for rendering text in OpenGL. I use TextMeasurer.TryMeasureCharacterBounds() to get the bounding boxes of all the characters to be drawn, and I use TextMeasurer.Measure() to get the render size (?) of each character individually, so that I can create an image of that size and render the character to it, and then write the data to my texture atlas. However, I'm confused about how the render size relates to the bounding box.. I need to use the render size to figure out the source and destination rectangles when rendering the text, but then I don't know how to position the destination rectangle with respect to the bounding box location returned by TryMeasureCharacterBounds(). Can someone help me out with this? With some fonts, the bounding box is sometimes wider than what is returned by TextMeasurer.Measure(), which is also confusing. Which should I be using to figure out the image size for rasterizing a single character?

**Comment by tocsoft** [comment]
TextMeasurer.Measure()  measures the text as a hole including line spacing etc.
 TryMeasureCharacterBounds() will return the bounding box of the individual glyphs.

however to truly leverage this library i would actaully recommend you integrate at the at the renderer level you can see how we are doing this for ImageSharp here https://github.com/SixLabors/ImageSharp.Drawing/blob/e2327992848f5b7ea19ed35fac735b82d4793b73/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor%7BTPixel%7D.cs#L129 this is a caching renderer that will only rasterize each glyph once but this will correctly handle things like kerning and (in future implementations font hinting) and even ligatures correctly without the naive solution. 

The IGlyphRenderer will provide you with all the information you need to fully control the rendering pipeline ithout having to reinvent layout etc..

**Comment by tocsoft** [comment]
closing this now as I feel this isn't an 'Issue' more of a question... if the above doesn't answer you or you have found an issue we can always reopen.
