### ISSUE TITLE
Provide installed fonts collection

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#14]
Add cross platform system for enumerating all the fonts installed on a users machine and expose them as a `FontCollection`.

Most OSs have a standard location where fonts will be installed

#### On Linux
- **~/.fonts/** - for your own fonts.
- **/usr/local/share/fonts/** - system-wide, user installed fonts.
- **/usr/share/fonts/** - system's font location.

#### On mac OS
- **~/Library/Fonts/** - Each user has complete control over the fonts installed in their Home. These fonts are available to that user when he or she is logged in to the computer. Fonts installed here are not available to all users of the computer.
- **/Library/Fonts/** - Any local user of the computer can use fonts installed in this folder. Mac OS X does not require these additional fonts for system operation. An admin user can modify the contents of this folder. This is the recommended location for fonts that are shared among applications.
- **/Network/Library/Fonts/** - The Network folder is for fonts shared among all users of a local area network. This feature is normally used on network file servers, under the control of a network administrator.
- **/System/Library/Fonts/** - Mac OS X requires fonts in this folder for system use and displays. They should not be manually altered or removed.
- **/System Folder/Fonts/** - This folder contains fonts used by the Classic environment (Mac OS X v10.4 or earlier only). If more than one Mac OS 9.1 System Folder is present, only fonts in the System Folder selected in the Classic pane of System Preferences are used. Classic applications can access only these fonts, not those stored elsewhere. Conversely, Mac OS X applications can use these fonts, even when the Classic environment is not active.

#### On windows
- **%SYSTEMROOT%\Fonts** - usually c:\Windows\Fonts 

depend on #13

**Comment by tocsoft** [comment]
partially supported, Windows only until I can access and test other OSs

currently works for truetype fonts installed in the **Windows** font directory, the collection can be accessed via

```c#
var systemFontCollection = FontCollection.SystemFonts;
```
or see which families are installed in the system
```c#
var systemFontsList = FontCollection.SystemFonts.Families;
```

**Comment by tocsoft** [comment]
now works for linux & mac (I haven't got a mac to test it one but it should work)

**Comment by EgoPingvina** [comment]
![image](https://github.com/SixLabors/Fonts/assets/9804340/de849e6b-e52b-403d-b884-ed65276cb145)
`FontCollection` does not contain a definition  for `SystemFonts`

**Comment by James-Jackson-South** [comment]
`SystemFonts` contains a `FontCollection` as a static property.

https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.SystemFonts.html#SixLabors_Fonts_SystemFonts_Collection

Please do not comment on long closed issues.

**Comment by JimBobSquarePants** [comment]
`SystemFonts` contains a `FontCollection` as a static property.

https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.SystemFonts.html#SixLabors_Fonts_SystemFonts_Collection

Please do not comment on long closed issues.
