### ISSUE TITLE
System.NullReferenceException thrown by FontFamily == operator

### ISSUE THREAD

**Issue by woutware** [SixLabors/Fonts#143]
This bug is new, this used to work fine.

Program to reproduce:

```
            FontFamily fontFamily = null;
            if (fontFamily == null) {
                Console.WriteLine("null");
            }
```

**Comment by woutware** [comment]
Not urgent by the way, I've worked around it by using object.ReferenceEqual(fontFamily, null).

**Comment by JimBobSquarePants** [comment]
Thanks... Yeah looks like change was here. Easy to fix.

https://github.com/SixLabors/Fonts/commit/5bc4b7a5c77d94ef598f743d057292edb86f875c#diff-5635c66fbd4380d20ba694114f623235R103
