### ISSUE TITLE
Unicode values off-by-one on icon fallback fonts

### ISSUE THREAD

**Issue by parzivail** [SixLabors/Fonts#144]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Fonts
- [X] I have verified if the problem exists in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using fallback fonts, unicode codepoints are off by one.

### Steps to Reproduce
1. Obtain icon font, e.g. Microsoft's [Segoe MDL2 Assets](https://aka.ms/SegoeFonts) (used because the webpage [lists unicode codepoints](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font))
2. Load font and draw specific codepoint with fallback

```csharp
var fonts = new FontCollection();
fonts.Install("path/to/normal/font/Arial.ttf");
fonts.Install("path/to/SegMDL2.ttf");
var normalFont = fonts.Find("Arial");
var iconFont = fonts.Find("Segoe MDL2 Assets");

var image = new Image<Rgb24>(512, 512);
var textGraphicsOptions = new TextGraphicsOptions(new GraphicsOptions(), new TextOptions { FallbackFonts = { iconFont } });

image.Mutate(g => g.DrawText(textGraphicsOptions, "\uE95D", normalFont.CreateFont(36), Color.Black, PointF.Empty));
```
3. Discover that the drawn glyph is not U+E95D but instead is U+E95E.

### System Configuration

- Fonts version: 1.0.0-beta0012
- Other Six Labors packages and versions: SixLabors.ImageSharp 1.0.0-rc0002, SixLabors.ImageSharp.Drawing 1.0.0-beta0009
- Environment (Operating system, version and so on): Windows 10 Pro 10.0.18363 Build 18363
- .NET Framework version: .NET Standard 2.1
- Additional information:

**Comment by parzivail** [comment]
I have discovered that this is an issue with certain revisions of fonts not corresponding to their out-of-date documentation.

**Comment by parzivail** [comment]
Actually, this seems to happen only to some codepoints. I have edited the original body accordingly.

**Comment by woutware** [comment]
Try beta0013, this sounds like it could be same issue as this one: https://github.com/SixLabors/Fonts/issues/140. In general just check with the latest beta before submitting an issue.

**Comment by parzivail** [comment]
You're right, my apologies. I drafted this issue and did testing before the new `ImageSharp.Drawing` update found its way to me, through which I am getting `Fonts` as a dependency. `beta0013` fixes this.
