### ISSUE TITLE
Ligature's - Add support for ligatures as this is an import feature for correctly rendering Arabic scripts

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#150]
Add support for ligatures... will help all fonts but they are mandatory for supporting Arabic scripts.

for some reading that might help - https://www.w3.org/TR/alreq/

**Comment by asaadbaw** [comment]
Hello

I am moving to uwp apps. I invested some time with this library. Unfortunately, it is not supporting Arabic. is there any fix or workaround?

**Comment by JimBobSquarePants** [comment]
https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#ligature-glyph-table

**Comment by JimBobSquarePants** [comment]
@tocsoft I've been having a look at [LayoutFarm.Typography](https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Typography.OpenFont/Tables.AdvancedLayout/LigatureCaretListTable.cs) to see how they implement the table linked above but can't figure out how to fit it into our architecture. Any hints?

**Comment by JimBobSquarePants** [comment]
If anyone is curious I've moved the milestone for this to RC1 made great progress via #198 

I could do with a little help filling in some of the gaps in the `LookupSubTable` implementations though. Does anyone here read either Rust or C++ well?
