### ISSUE TITLE
Parameter to control text line height/leading

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/Fonts#152]
Follow-up on SixLabors/ImageSharp.Drawing#112:

We need to introduce a parameter in title in [RenderOptions](https://github.com/SixLabors/Fonts/blob/4beaff16420c706a10c293cca6e1c1037a420d36/src/SixLabors.Fonts/RendererOptions.cs).

That parameter should then somehow alter the following `offset` value:
https://github.com/SixLabors/Fonts/blob/4beaff16420c706a10c293cca6e1c1037a420d36/src/SixLabors.Fonts/TextLayout.cs#L279

/cc @tocsoft @JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
So I've been doing some reading and according to these [Flutter docs](https://www.flutterinternals.org/text/text-rendering) LineHeight appears to be a combination of the `Leading` value (_additional spacing split evenly above and below the line_) and the font `Height` value (height (_ascent plus descent)_).

However, we calculate the `Font.LineHeight` property as `TypoAscender` - `TypoDescender` + `TypoLineGap` based on the [Microsoft docs](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#tad).

This, as you can imagine, leads me to some confusion. 

@tocsoft I'll definitely need your guidance here. Should we be simply adding a `LineHeight` property? and calculating everythgin from that?

**Comment by tocsoft** [comment]
I wouldn't add a `LineHeight` property instead we should be provide a `LineSpacing` property (which is how such a feature is presented in Word) and if we are using Word as a strategy then it should be a multiply we apply the calculated `LineHeight`.

So if you want to increase the spacing between the lines you would provide a number > 1 and to get lines closer a value < 1 with one being our current size and default value.... I also would not stop negative values as I can see it producing some interesting results and can't see why it would break anything.

**Comment by JimBobSquarePants** [comment]
Is Word something we want to base our approach on? 

Perhaps we should follow the WC3 CSS Fonts Module Level 4 spec and provide overrides for `ascent`, `descent`, and `line-gap`?

https://www.w3.org/TR/css-fonts-4/#font-metrics-override-desc

I'm trying to figure out what Skia and System.Drawing do but it's bizarrely difficult to discover an straight answer.

**Comment by JimBobSquarePants** [comment]
Ok @tocsoft I did some reading and, as ever, your plan is definitely the most sane!

I'm assuming applying the value would be as simple as this then?

``` c#
var offset = new Vector2(0, (lineHeightOfFirstLine * options.LineSpacing) - top);
```
