### ISSUE TITLE
Accents are not centred correctly on lower case i.

### ISSUE THREAD

**Issue by SSL-Julian** [SixLabors/Fonts#158]
Accents for these characters ìíîï do not render in the correct position.
I have modified the font sample to output an image that shows the problem.

![ì í î ï arial](https://user-images.githubusercontent.com/43008955/103675270-a7367a80-4f77-11eb-80be-d43af6ad5946.png)

**Comment by JimBobSquarePants** [comment]
Please fill in the template you were provided when opening this issue.

**Comment by SSL-Julian** [comment]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Fonts
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Accents for these characters ìíîï do not render in the correct position.
I have modified the font sample to output an image that shows the problem.

### Steps to Reproduce

Get the sample from Fonts/samples/DrawWithImageSharp/
Modify Program.cs Line 44 from  RenderText(font, "abc", 72); to  RenderText(font, "ìíîï", 72);
Notice in the created images that the accents are not positioned directly over the i character.

### System Configuration
- Fonts version: v1.0.0-beta0013
- Other Six Labors packages and versions: SixLabors.ImageSharp.Drawing 1.0.0-beta11
- Environment (Operating system, version and so on): Windows 10 Home version 10.0.19042 64 bit
- .NET Framework version: .NET Core 3.1.10
- Additional information:

**Comment by JimBobSquarePants** [comment]
Thanks. I'll have a look.
