### ISSUE TITLE
SystemFont not finding user's installed fonts

### ISSUE THREAD

**Issue by 21repierre** [SixLabors/Fonts#162]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Fonts
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

On Windows when someone install a font without clicking "Install for all users", the font will be installed in the folder _"%userprofile%\AppData\Local\Microsoft\Windows\Fonts"_ and not in _"C:\Windows\Fonts"_.

### Steps to Reproduce

In this case, doing `SystemFonts.Find("myfont");` will throw an error because it's not searching in _"%userprofile%\AppData\Local\Microsoft\Windows\Fonts"_

### System Configuration

- Fonts version: 1.0.0-beta0013
- Other Six Labors packages and versions: ImageSharp-1.0.3, ImageSharp.Drawing-1.0.0-beta11
- Environment (Operating system, version and so on): Windows 10 20H2
- .NET Framework version: .NET Core 5.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Can you please rewrite this issue using the provided template. We need all the specified required information.

**Comment by 21repierre** [comment]
I'm sorry but could you provide a link to this template? I can't find it

**Comment by JimBobSquarePants** [comment]
Normally the template appears when you click "New Issue". If that didn't appear for you I'd love to know your navigation process so I can raise an issue with GitHub.

![image](https://user-images.githubusercontent.com/385879/109080073-d788d280-76f7-11eb-8f1a-292597bf53ff.png)
![image](https://user-images.githubusercontent.com/385879/109080104-e96a7580-76f7-11eb-9d39-100a42e21058.png)

I'll update your original comment with the template layout so if you can fill in the rest of the details that would be greatly appreciated. Thanks!

**Comment by 21repierre** [comment]
I don't remember seeing this menu before creating the issue. However when I tried again, it showed up.
Also, I've updated the issue with (I hope) all the details you need.

**Comment by JimBobSquarePants** [comment]
Ok... So the feature has only been available since Windows 10 1809. 

I think this is a reasonable feature request. Feel free to have a go!

It should be as simple as adding the following locations

```
"%APPDATA%\\Microsoft\\Windows\\Fonts"
"%LOCALAPPDATA%\\Microsoft\\Windows\\Fonts"
```

to the `SystemFontCollection`.


https://github.com/SixLabors/Fonts/blob/8989989b098ea6ed3f64bc9b85f9fd5333ac75a5/src/SixLabors.Fonts/SystemFontCollection.cs#L23-L40
