### ISSUE TITLE
Fallback Fonts break kerning

### ISSUE THREAD

**Issue by jb-modist** [SixLabors/Fonts#171]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Fonts
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Mixing fonts within the same text such as "亞DARKSOUL亞" causes incorrect character spacing
![image](https://user-images.githubusercontent.com/63240621/117309414-4ca42100-ae7a-11eb-9e87-c4892969bc85.png)
Adding a check in GenerateLayout to rescale if the previous glyph fell back to a different font fixes the issue...
```c#
if (previousGlyph != null && glyph.Font != previousGlyph.Font)
{
    scale = glyph.Font.EmSize * 72;
}
```
![image](https://user-images.githubusercontent.com/63240621/117309617-7fe6b000-ae7a-11eb-9118-9eb32940dd3a.png)

### Steps to Reproduce
Simple Console Project:
```c#
class Program
{
    static void Main(string[] args)
    {
        string outpath = args[0];
        var image = new Image<Rgba32>(600, 600);
        FontCollection collection = new FontCollection();
        var whitney = collection.Install("whitney-book.ttf");
        var YaHei = collection.InstallCollection("msyh.ttc");
        var Malgun = collection.Install("malgun.ttf");
        var font = whitney.CreateFont(25);
        DrawingOptions options = new DrawingOptions();
        options.GraphicsOptions = new GraphicsOptions() { Antialias = true };
        options.TextOptions = new TextOptions() { DpiX = 96, DpiY = 96, ApplyKerning = true };
        options.TextOptions.FallbackFonts.Add(Malgun);
        foreach (var f in YaHei)
            options.TextOptions.FallbackFonts.Add(f);
        // MINI LEGEND
        image.Mutate(x => x.DrawText(options, "The quick brown 왓 jumps over the lazy dog", font, Color.White, new PointF(0, 0)));
        image.Mutate(x => x.DrawText(options, "왓45", font, Color.White, new PointF(0, 50)));
        image.Mutate(x => x.DrawText(options, "123456789", font, Color.White, new PointF(0, 100)));
        image.Mutate(x => x.DrawText(options, "亞DARKSOUL亞", font, Color.Black, new PointF(0, 150)));
        image.SaveAsPng(outpath);
    }
}
```

### System Configuration

- Fonts version:
- Other Six Labors packages and versions:
- Latest SixLabors.Fonts downloaded as a zip
- Latest ImageSharp.Drawing downloaded as a zip
- Environment (Operating system, version and so on):
- Windows 10
- .NET Framework version:
- .net 5.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Thanks @jb-modist for providing so much information. Would it be possible for you to provide the line number where you added the fix? It's difficult to see where it should be.

**Comment by JimBobSquarePants** [comment]
Can you please give https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.Fonts/1.0.0-beta13.5.9 a try. That should fix the issue for you.
