### ISSUE TITLE
Helvetica characters are note rendered properly (rendered as rectangles) on macOS

### ISSUE THREAD

**Issue by 0xced** [SixLabors/Fonts#191]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode (I have only tested with the NuGet package)
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When rendering text with the Helvetica font on macOS, characters are not rendered properly, they all appear as rectangles.

### Steps to Reproduce

Create the following two files (`RenderHelvetica.csproj` + `Program.cs`) and execute `dotnet run` in the directory in which they were saved. This creates two files, `hello-Arial.png` and `hello-Helvetica.png`.

Arial renders properly:
![hello-Arial](https://user-images.githubusercontent.com/51363/129091702-c4608c0f-5263-43f9-8401-7fe991c196a2.png)

Helvetica fails to render properly (only rectangles are rendered):
![hello-Helvetica](https://user-images.githubusercontent.com/51363/129091744-047381d1-4155-482e-a665-30e49173b60a.png)

RenderHelvetica.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta13" />
  </ItemGroup>

</Project>
```

Program.cs
```csharp
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

const int margin = 10;
const int fontSize = 24;
const string text = "Hello World!";

foreach (var fontName in new[] { "Arial", "Helvetica" })
{
    var fontFamily = SystemFonts.Find(fontName);
    var font = new Font(fontFamily, fontSize);
    var rectangle = TextMeasurer.Measure(text, new RendererOptions(font));
    var image = new Image<Argb32>((int)rectangle.Width + margin * 2, (int)rectangle.Height + margin * 2, Color.Black);
    image.Mutate(x => x.DrawText(text, font, Color.White, new PointF(margin, margin)));
    image.SaveAsPng($"hello-{fontName}.png");
}
```

### System Configuration

- ImageSharp.Drawing version: **1.0.0-beta13**
- Other ImageSharp packages and versions (transitive dependencies):
  - SixLabors.Fonts: **1.0.0-beta15**
  - SixLabors.ImageSharp: **1.0.3**
- Environment (Operating system, version and so on): macOS 10.15.7 (19H1323)
- .NET Framework version: .NET SDK 5.0.302 and .NET Core 5.0.8

Note: I have not tested on Windows nor Linux since the Helvetica font is not installed on those operating systems.

**Comment by 0xced** [comment]
After some investigation, I found out what's happening. The rendered glyphs are fallback glyphs because no standard glyph can be found as the CMapTable ends up being empty. The CMapTable is empty because no `CMapSubTable` is ever created in `SixLabors.Fonts.Tables.General.CMapTable.Load`. The Helvetica font has 10 encodings, 1 _Unicode_ and 9 _Macintosh_ so the [foreach loop](https://github.com/SixLabors/Fonts/blob/c570014fc42ca504ecc2655a19aaca031403f433/src/SixLabors.Fonts/Tables/General/CMapTable.cs#L87) filtering out non-Windows encoding prevents `CMapSubTable` instances to be created.

If I remove the filter (i.e. delete `Where(x => x.PlatformID == PlatformIDs.Windows)`) then the `Hello World!` text renders properly. According to the comments on [line 42](https://github.com/SixLabors/Fonts/blob/c570014fc42ca504ecc2655a19aaca031403f433/src/SixLabors.Fonts/Tables/General/CMapTable.cs#L42) (_use the best match only_) and [line 52](https://github.com/SixLabors/Fonts/blob/c570014fc42ca504ecc2655a19aaca031403f433/src/SixLabors.Fonts/Tables/General/CMapTable.cs#L52) (_didn't have a windows match just use any and hope for the best_) it looks like the code in `TryGetGlyphId` is expecting that `Tables` may contain non-Windows encoding but this is impossible with the `Where` clause I described just above.

Since I'm not familiar with font tables and I just skimmed over the [cmap — Character to Glyph Index Mapping Table](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap) documentation I'd like someone more familiar with this codebase (@tocsoft maybe?) confirm that deleting `Where(x => x.PlatformID == PlatformIDs.Windows)` is the correct fix for this issue.

**Comment by JimBobSquarePants** [comment]
I'm just looking at that exact section! 😄 

My findings are the same. I'm reading through at the moment and my initial testing indicates no problems so far, I'll double check and let you know.
