### ISSUE TITLE
EndOfStreamException attempting to LoadDescription of font  (PT Dingbats 1)

### ISSUE THREAD

**Issue by jafin** [SixLabors/Fonts#203]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Fonts
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Attempting to read font description of a certain ttf file throw the error.
Numerous other fonts are all loading fine.

Version used: 1.0.0-beta15

Font can be found here: http://www.easfina.com.au/fonts/BRDB1RT0.TTF
Described as "PT Dingbats 1"  Version 1.20

```c#
Exception thrown: 'System.IO.EndOfStreamException' in SixLabors.Fonts.dll
End of stream reached with 2 byte left to read.
```

### Steps to Reproduce

```c#
 static void Main(string[] args)
 {
    FontDescription fontDescription = FontDescription.LoadDescription("C:\\temp\\BRDB1RT0.TTF");
 }
```

### Possible Reason

The font is being identified as `Version 1`
From reading this https://docs.microsoft.com/en-us/typography/opentype/spec/os2
My understanding is it will not have some of the fields available in later version specs.

In OS2table.cs  318, if I amend it as per below, description is loaded and the streadreader exception is avoided.

```c#
 if (version > 1) //fields not in v1 https://docs.microsoft.com/en-us/typography/opentype/spec/os2
      {
          heightX = reader.ReadInt16();
          capHeight = reader.ReadInt16();
          defaultChar = reader.ReadUInt16();
          breakChar = reader.ReadUInt16();
          maxContext = reader.ReadUInt16();
      }
```

### System Configuration
- Windows 10 
- VS2019

- Fonts version: PT Dingbats 1" Version 1.20
- Other Six Labors packages and versions: --nill
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: NET 5
- Additional information: Discovered using PDFSharpCore, which utilises this library.

**Comment by JimBobSquarePants** [comment]
@jafin Good diagnosis! That table loader needs a little cleanup. Would it be possible to PR a fix?
