### ISSUE TITLE
Error: Invalid glyph format when performing FontCollection.Install

### ISSUE THREAD

**Issue by SamVanhoutte** [SixLabors/Fonts#226]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Fonts
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When executing the lines of code below, on my development environment (.net5.0 on macOS with Rider), the below happens.

**Exception**

`InvalidFontFileException: Invalid glyph format, only TTF glyph outlines supported`

**Callstack**

```
SixLabors.Fonts.FontReader..ctor(Stream stream, TableLoader loader)
SixLabors.Fonts.FontReader..ctor(Stream stream)
SixLabors.Fonts.FontDescription.LoadDescription(string path)
SixLabors.Fonts.FileFontInstance..ctor(string path, long offset)
SixLabors.Fonts.FileFontInstance..ctor(string path)
SixLabors.Fonts.FontCollection.InstallInternal(string path, CultureInfo culture, out FontDescription fontDescription)
SixLabors.Fonts.FontCollection.InstallInternal(string path, CultureInfo culture)
SixLabors.Fonts.FontCollection.Install(string path)
````

### Steps to Reproduce

**Code**

```csharp
var fonts = new FontCollection();
var lightFamily = fonts.Install(Path.Combine(_hostingEnvironment.WebRootPath, "fonts/merkury_bold.otf"));
```

### System Configuration

- Fonts version: **nuget 1.0.0-beta15**
- Other Six Labors packages and versions: **SixLabors.ImageSharp==1.0.4**, **SixLabors.ImageSharp.Drawing==1.0.0-beta13**, **SixLabors.ImageSharp.Web==1.0.4**
- Environment (Operating system, version and so on): macOS Big Sur (11.6)
- .NET Framework version: 5.0
- Additional information: Similar issue reported #29 , but that was with SystemFonts, as was closed as fixed.

**Comment by JimBobSquarePants** [comment]
Does the font (you've not provided it) have TTF glyph outlines? can you provide it?

**Comment by JimBobSquarePants** [comment]
Hi @SamVanhoutte Can you please supply the font in question?

**Comment by SamVanhoutte** [comment]
Apologies for this.  missed it (and worked around by using a different font).
You can find / download the font here: https://github.com/SamVanhoutte/cotacol-site/blob/main/src/CotacolApp/wwwroot/fonts/merkury_bold.otf

(not possible to upload otf files, here, it seems)

**Comment by SamVanhoutte** [comment]
So, that probably means, you can close this issue, as it is related to my lack of understanding/knowledge on font-specifics.  Thanks for your feedback and help!  
And appreciating the work you guys deliver <3
