### ISSUE TITLE
Strange "Bleeding" fonts

### ISSUE THREAD

**Issue by dotnetnoobie** [SixLabors/Fonts#23]
I am not sure if this is related to the actual fonts been badly made or if it is an issue also with the "Shapes" libary... It looks like the shapes being drawn for the font charaters are missing a point and therefore assume a point of 0,0 

It is not all fonts only a few I have found in the "Serif" section of Google Fonts 

I have the latest packages of
ImageSharp - 1.0.0-alpha5-00069
ImageSharp.Drawing - 1.0.0-alpha5-00063
SixLabors.Fonts - 0.1.0-alpha0006
SixLabors.Shapes - 0.1.0-alpha0010

I have found a number of fonts that do this a few listed below (all downloaded from google fonts)
Marko One
Coustard
Wendy One

The image is an example of the issue with these fonts, again this was made using the method from the Text Wrapping demo https://github.com/SixLabors/Demos/blob/master/WaterMarkSample/Program.cs#L71

![bleeding shapes-fonts](https://cloud.githubusercontent.com/assets/5423598/25007957/6ba0bc74-208c-11e7-93c7-120fe5716b5b.png)

**Comment by tocsoft** [comment]
ooh that's an interesting one, definitely looks like I have an issue with the 'o's in that font. The 'p' and 'q' look like they are having a similar issues. 

I think your right looks like I'm loosing part of the curve.

**Comment by dotnetnoobie** [comment]
Here is a few more examples (all using the same text content, different fonts)

Font: Macondo-Regular

![macondo-regular](https://cloud.githubusercontent.com/assets/5423598/25013516/0e1d6ef0-209e-11e7-8bb6-47f11231dfd7.png)


Font: WendyOne-Regular

![wendyone-regular](https://cloud.githubusercontent.com/assets/5423598/25013341/69ee031c-209d-11e7-8cb0-9bb42d410fe7.png)


Font: MarkoOne-Regular

![markoone-regular](https://cloud.githubusercontent.com/assets/5423598/25013585/5954b5c2-209e-11e7-980a-2f8f88fac68f.png)


Font: DellaRespira-Regular

![dellarespira-regular](https://cloud.githubusercontent.com/assets/5423598/25013683/ce3c602e-209e-11e7-80ac-fb2e6d88158f.png)

**Comment by tocsoft** [comment]
fixed in versions 0.1.0-ci0058 (myget) & 0.1.0-alpha0007 (nuget)
