### ISSUE TITLE
The letter "J" is offset to the left

### ISSUE THREAD

**Issue by dotnetnoobie** [SixLabors/Fonts#24]
The letter "J" always seems to be a little bit offset to the left

some examples 

![94873214-e7d6-4720-8761-b4a1dd68184b](https://cloud.githubusercontent.com/assets/5423598/25039495/06bac28a-212e-11e7-91d8-0c0167d4484e.png)
![4be662d8-16dd-443d-b96f-486ceb6a3909](https://cloud.githubusercontent.com/assets/5423598/25039494/06b9f0f8-212e-11e7-8e85-d199c72e834c.png)
![untitled](https://cloud.githubusercontent.com/assets/5423598/25039496/06cdf710-212e-11e7-8168-ebeac47fb5bd.png)

**Comment by tocsoft** [comment]
this was to do with my trying to apply a character offset based on a left side bearing when I shouldn't.. I've remove that offset so the j should now render correctly in the next release. I'll update with the version number once deployed.

**Comment by tocsoft** [comment]
fixed in versions 0.1.0-ci0058 (myget) & 0.1.0-alpha0007 (nuget)

**Comment by dotnetnoobie** [comment]
thanks I will give it a try in the latest vesion
