### ISSUE TITLE
SixLabors.Fonts  Version 1.0.0-beta15 upgrade to 1.0.0-beta16 function SystemFonts.Find not recognized

### ISSUE THREAD

**Issue by HenriApperloo** [SixLabors/Fonts#242]
SixLabors.Fonts  Version 1.0.0-beta15 upgrade to 1.0.0-beta16 function SystemFonts.Find not recognized

- Other Six Labors packages and versions:
    <PackageReference Include="SixLabors.Fonts" Version="1.0.0-beta15" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.4" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta13" />

**Comment by JimBobSquarePants** [comment]
Closed. Unfilled template.
