### ISSUE TITLE
TextMeasurer.Measure and IImageProcessingContext.DrawText fail if the first character is a /

### ISSUE THREAD

**Issue by Steven-Berry** [SixLabors/Fonts#244]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Fonts
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Measuring or drawing text that starts with a forward slash / fails with an ArgumentOutOfRangeException
This appears to be located in DefaultShaper.AssignFeatures
`if (shapingData.CodePoint == FractionSlash || shapingData.CodePoint == Slash)`
This will call 
`shapingData = collection.GetGlyphShapingData(start - 1);`
when start == 0

### Steps to Reproduce
```
var font = SystemFonts.CreateFont("Arial", 12);
var rendererOptions = new TextOptions(font)
{
    WrappingLength = 100,
    Origin = new PointF(0, 0)
};
var measurement = TextMeasurer.Measure("/ This will fail", rendererOptions);
```

### System Configuration
Windows 10 and AWS Linux 2

- Fonts version: SixLabors.Fonts 1.0.0-beta16
- Other Six Labors packages and versions: SixLabors.ImageSharp 2.0.0, SixLabors.ImageSharp.Drawing 1.0.0-beta14
- Environment (Operating system, version and so on): Windows 10/AWS Linux 2
- .NET Framework version: .NET 6.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
[1.0.0-beta16.6](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.Fonts/1.0.0-beta16.6) contains a fix.

**Comment by woutware** [comment]
@JimBobSquarePants Is there a date on when a nuget bugfix release is coming? Our nuget software release is referencing beta16 currently, and our customers are affected by this problem.

**Comment by JimBobSquarePants** [comment]
I wasn’t planning on a NuGet release until the RC but since it’s a fairly critical bug I’ll get something pushed out in the next few days.

**Comment by woutware** [comment]
@JimBobSquarePants  Thanks for the nuget release.
