### ISSUE TITLE
Error when using TextMeasure.measure on some fonts

### ISSUE THREAD

**Issue by bodamithun** [SixLabors/Fonts#269]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Fonts
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Error when using TextMeasure.Measure feauture

- Fonts version: 1.0.0-beta17
- Other Six Labors packages and versions:
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: .net core 3.1

- Additional information:

I recently upgraded  SixLabors.Fonts from 1.0.0-beta0009 to 1.0.0-beta17, also I upgraded the imagesharp and imageSharp.Drawing to latest versions and I see that some of the fonts are failing with the following exception

"Invalid value for 'subTableFormat' 7294. Should be '1'

These were working before I did the upgrade. Following code is throwing the error. And also this is not happening with all the fonts... only few fonts.

AllFontCollection = new FontCollection();
AllFontCollection.Add(@"Fonts/font1.ttf");
AllFontCollection.Add(@"Fonts/font2.ttf");
if (fontCollectionService.AllFontCollection.TryGet(layer.Font.FontName, out FontFamily family))
{
            // family will not be null here
            font = family.CreateFont((float)(layer.Font.FontSize * 4), fontStyle);
}
var textOptions = new TextOptions(font) { WrappingLength = targetWidth };

var textSize = TextMeasurer.Measure(text, textOptions ); //this line throws exception

am I missing anything?

I would really appreciate any direction on this...

Thanks in advance...

[fonts.zip](https://github.com/SixLabors/Fonts/files/8832865/fonts.zip)

**Comment by JimBobSquarePants** [comment]
You’ll need to supply the font or else there is nothing we can do.

**Comment by bodamithun** [comment]
Thanks Jim,

I have attached a font that is failing.

**Comment by bodamithun** [comment]
Thanks Brian for looking into this...


My question is that the same font worked with old version of SixLabors.Fonts(1.0.0-beta0009). 

Why would it start failing with the new version?

**Comment by brianpopow** [comment]
> Thanks Brian for looking into this...
> 
> My question is that the same font worked with old version of SixLabors.Fonts(1.0.0-beta0009).
> 
> Why would it start failing with the new version?

With #198, we have introduced advanced font shaping capabilities and this requires those lookup tables to be parsed correctly.

I am not sure at the moment how we can deal with this. Maybe we can introduce a 'none strict' parsing mode, which will ignore invalid tables, but I am not sure, if that's a good idea. Maybe it leads to incorrect rendering results, because of this missing table.

The font has also other errors: some glyph bounding boxes are reported to be incorrect.

Here is the full report:
[AliceFrancesHMK-Regular.ttf.report.zip](https://github.com/SixLabors/Fonts/files/8834364/AliceFrancesHMK-Regular.ttf.report.zip)

**Comment by loraderon** [comment]
> I am not sure at the moment how we can deal with this. Maybe we can introduce a 'none strict' parsing mode, which will ignore invalid tables, but I am not sure, if that's a good idea. Maybe it leads to incorrect rendering results, because of this missing table.
> 
> The font has also other errors: some glyph bounding boxes are reported to be incorrect.

Relaxed parsing maybe should be an option to look into since the font _seems fine_ to the average user? It can be opened, previewed and installed in Windows 11.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/76928/173053798-c6bdfc2a-17c1-448b-9c9b-ba6e4792bea8.png">

**Comment by JimBobSquarePants** [comment]
We’ll just have a look at how one of the libraries we’ve been referencing handles it and copy that. Fonts are so complicated internally there’s gonna be some spec issues in the wild.

**Comment by brianpopow** [comment]
I tried fontkit version 1.8.0: It fails with:

```
Error: Unknown version 7294
    at VersionedStruct.decode (F:\vsprojekte\fontkit\node_modules\restructure\src\VersionedStruct.js:37:15)
    at VersionedStruct.decode (F:\vsprojekte\fontkit\node_modules\restructure\src\VersionedStruct.js:40:23)
    at F:\vsprojekte\fontkit\node_modules\restructure\src\Pointer.js:69:30
    at Pointer.decode (F:\vsprojekte\fontkit\node_modules\restructure\src\Pointer.js:79:16)
...
```

**Comment by loraderon** [comment]
Would you be interested in a PR that enables relaxed/unsafe lookup tables? The fallback would probably always be '1'.
I suppose it would be a setting on FontCollection.

I tried this font and changed `LookupType5SubTable` & `LookupType6SubTable` to return '1' and then the text could be measured. I do not have any knowledge of the font formats or specifications so I do not really know if this idea is even feasable.

**Comment by brianpopow** [comment]
> Would you be interested in a PR that enables relaxed/unsafe lookup tables? The fallback would probably always be '1'. I suppose it would be a setting on FontCollection.
> 
> I tried this font and changed `LookupType5SubTable` & `LookupType6SubTable` to return '1' and then the text could be measured. I do not have any knowledge of the font formats or specifications so I do not really know if this idea is even feasable.

PR's are always welcome, but I dont think returning always 1 is a good solution. This may work with the particular font, but will fail in other cases.

I have checked how harfbuzz handles it and it seems they do not throw an exception, but instead return a default (null?) instead: https://github.com/harfbuzz/harfbuzz/blob/17c80035adc61c52a9e9600664496e3e4b837e37/src/hb-ot-layout-gsubgpos.hh#L3681

I am not sure about the consequences, if we just ignore a lookup table. I am afraid this will cause trouble elsewhere.

**Comment by loraderon** [comment]
> I have checked how harfbuzz handles it and it seems they do not throw an exception, but instead return a default (null?) instead: https://github.com/harfbuzz/harfbuzz/blob/17c80035adc61c52a9e9600664496e3e4b837e37/src/hb-ot-layout-gsubgpos.hh#L3681
> 
By returning `null` and handle nulls with `if (subTable?.TrySubstitution(fontMetrics, table, collection, feature, index, count) == true)` also "works".

> I am not sure about the consequences, if we just ignore a lookup table. I am afraid this will cause trouble elsewhere.

Maybe the setting could be called `HereBeDragonsUnsafeLookupTablesFallbackDoNotReportIssues` 😆 

My reasoning is that the font works and I would have no idea as to why this library cannot use it. It would feel like a bug that has no workaround.

**Comment by brianpopow** [comment]
> By returning `null` and handle nulls with `if (subTable?.TrySubstitution(fontMetrics, table, collection, feature, index, count) == true)` also "works".

I think that should work, I am in favor of this solution. @JimBobSquarePants what do you think, should we go this route?

> Maybe the setting could be called `HereBeDragonsUnsafeLookupTablesFallbackDoNotReportIssues` 😆
> 

I like you creativity with naming, but I think we need another name 😄 

Also something we should consider is using the checksum in the table header. We should be able to determine such errors with it.

@loraderon before you start working on this let's wait what @JimBobSquarePants thinks about it.

**Comment by JimBobSquarePants** [comment]
We'll need to make the changes for both GPOS and GSUB `LookupListTable` types. The implementations are virtually identical so changes should be very similar.

I think we should try removing the strict parsing and return `NotImplementedSubTable` when the version number is incorrect for each subtable. That should allow us to avoid any null checks anywhere else in the codebase.

**Comment by loraderon** [comment]
`NotImplementedSubTable` seems much nicer and it gives the same results.

@JimBobSquarePants Should there be any setting or should we just always use `NotImplementedSubTable` and ignore the "invalid subTable" information?

**Comment by JimBobSquarePants** [comment]
We shouldn't require an additional setting. Strict adherence to the spec won't work for us in the wild.
