### ISSUE TITLE
Small font rendering really unclear (blurry, missing pixels etc)

### ISSUE THREAD

**Issue by myblindy** [SixLabors/Fonts#293]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Fonts
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Rendering small fonts is unreadable with alpha blending enabled, due to the really imprecise, blurry way they're being rendered:

ImageSharp (default antialiasing settings):
![image](https://user-images.githubusercontent.com/541998/181290216-50806d63-ae8e-4df1-8cdf-f3bcb7ae1719.png)

GDI+ (clear type):
![image](https://user-images.githubusercontent.com/541998/181290344-07b44b17-9929-4fad-a0c0-25650997d7c7.png)

This is with Segoe UI at 10 pixels. The vertical lines especially aren't clear, and with alpha blending enabled they just disappear. 

I also tried disabling antialiasing in the ImageSharp render, but that makes it even more obvious how imprecise it is:
![image](https://user-images.githubusercontent.com/541998/181290894-8f5dceca-b714-4c52-b156-eaf8d89054fe.png)

I also tried hinting, which is supposed to help with this, but it doesn't seem to work at all:
![image](https://user-images.githubusercontent.com/541998/181291168-e0b88986-210d-42c1-9c29-f39ee1e97251.png)

For Open Sans it's even less readable, and hinting just produces long vertical lines:
![image](https://user-images.githubusercontent.com/541998/181291623-4f5f1e20-d23f-434e-b3e3-b247fa459b4d.png)

Is there some set of options I can enable to make small font rendering clear?

### Steps to Reproduce
I have a sample repo that I used to generate those images at https://github.com/myblindy/font_test

### System Configuration

- Fonts version: 1.0.0-beta18
- Other Six Labors packages and versions: ImageSharp 2.1.3, ImageSharp.Drawing 1.0.0-beta15
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .Net 6
- Additional information: N/A

**Comment by JimBobSquarePants** [comment]
There's actually two issues here. 

1. The rasterizer. We need LCD rasterization to compete with System.Drawing. We just use alpha blending and it's simply no match. I know PixelFarm have an [implementation](https://github.com/PaintLab/PixelFarm/blob/ec7981fd5576c66d9aa7d1ebfca1718f1946f1d4/src/PixelFarm/PixelFarm.CpuBlit_Layer1/02_Rasterization/5_DestBitmapRasterizer.cs) but I don't know when I'd ever get round to adding it to ImageSharp.Drawing (that's where the rasterizer lives). @tocsoft have you ever dabbled in this?

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/385879/181546647-a0ba3a16-0dc5-44f4-b187-25552d445b50.png">

2. The hinting. That appears to be a problem with the X hinting and will require careful stepping through to figure out what is happening. That one is a little heartbreaking as I thought we'd cracked it. 😔 

Y-only hinting seems to be fine.
![a](https://user-images.githubusercontent.com/385879/181552002-cdcf6236-c565-4ca8-b370-0ec1bf82b6ca.png)

**Comment by JimBobSquarePants** [comment]
Noting that both XY and Y hinting work for the ttf version of OpenSans

**Comment by myblindy** [comment]
I had stopped using the ttf version because it crashed with NRE in the previous release, I'll give it a try again. 

So far I have this:

Segoe UI with Y hinting, still very blurry, and the vertical lines are not straight, look at `o` in particular:
![image](https://user-images.githubusercontent.com/541998/181576244-36a3b4b8-1b8d-40f4-b0e2-d225b1d758e3.png)

Open Sans (ttf) with XY hinting, looks okay shape-wise, but everything is blurred (ie, high transparency which breaks alpha blending against a non-black background):
![image](https://user-images.githubusercontent.com/541998/181577043-c9c1fbdd-772e-491d-b145-637c8e509df4.png)

**Comment by myblindy** [comment]
> Noting that both XY and Y hinting work for the ttf version of OpenSans
> 
> ![a](https://user-images.githubusercontent.com/385879/181563608-b4d87e00-c4d5-460d-9fa2-c4536179d52c.png)

Also note that white text on a transparent background doesn't render on github, it's why I'm taking screen shots :)

**Comment by JimBobSquarePants** [comment]
>Also note that white text on a transparent background doesn't render on github, it's why I'm taking screen shots :)

Haha! I completely forgot since I'm so used to dark mode! I'll update my images.

**Comment by tocsoft** [comment]
> ... @tocsoft have you ever dabbled in this? ...

nope not something i've experimented with, however I would say the issue with 'LCD' rendering is they only work for LCD displays (not paper etc) and also you need to know the subpixel layout of the screen and the exact position on the screen where it will render, you can't rasterize the pixels once and move them, for example, as moving the it half a pixel in any direction will cause the relative subpixels layout to be different in relation to the target.

**Comment by tocsoft** [comment]
I knew what you meant, but that technique can only be useful when rendering to screen where you can take advantage of the color shifting of the pixels rendered, it will produce fringing and be pretty useless in any other medium, and you also can't composite the rendered text on to another picture (post generation as there is not transparency retained). So unless your planning on rendering the vectors and displaying them directly to screen then it'll be very likely to produce suboptimal results. This is all remembering that real time screen graphics rendering is not a scenario we are actually targeting with this library.

FYI, Antigrain and Cleartype (which System.Drawing uses cause its a relatively thin wrapper around the GDI screen rendering subsystem system) are both screen rendering technologies they where built to draw pixels on a screen which is why it makes sense for them.

**Comment by JimBobSquarePants** [comment]
@tocsoft Ah right... I wonder whether it is something we should consider in the future though as it seems more people are beginning to use the library in gaming. I guess they can simply bring their own rasterizer.

@myblindy Looks like I may be having some success with the interpreter. Here's Segoe UI at 10 pixels and XY hinting.

![Assigning food to tree](https://user-images.githubusercontent.com/385879/181801924-68808b30-9132-40d5-8a4a-d783545fc495.png)

Here's with (left) and without (right) hinting.
<img alt="image" src="https://user-images.githubusercontent.com/385879/181804627-86f78ba5-2b81-4664-993c-49cd51b23c82.png">

I have a LOT of visual testing to do now.

**Comment by myblindy** [comment]
Definitely an improvement, great work! 

I'll keep an eye on how this shapes up (no pun intended), but for now I switched to the tried and true `System.Drawing` to get a working baseline version of the code. In the medium-to-long-term when cross-platform starts to matter I'll revisit ImageSharp and SkiaSharp and see where we stand!
