### ISSUE TITLE
TextLayout.ProcessText throws an unhandled exception while using Style Script font with specific text 

### ISSUE THREAD

**Issue by Kizuto3** [SixLabors/Fonts#298]
**Description**
I found a weird bug that occurs while using Style Script font and a specific text. An ArgumentOutOfRangeException is thrown.

**Steps to Reproduce**
```csharp
var content = "Please enter the text";

var fontFamilies = new FontCollection();

var fontFamily = fontFamilies.Add(@"<full path>\Style Script.ttf");

var font = fontFamily.CreateFont(16, FontStyle.Regular);

var renderOptions = new TextOptions(font)
{
    Dpi = 96,
    WrappingLength = 0f,
    VerticalAlignment = VerticalAlignment.Top,
    HorizontalAlignment = HorizontalAlignment.Left,
    KerningMode = KerningMode.Auto
};

var textBox = TextLayout.ProcessText(content.AsSpan(), renderOptions);
```
            
However, no exception is thrown if `content = "enter the text"`

**System Configuration**

- Fonts version: 1.0.0-beta18.2
- Other Six Labors packages and versions: none
- Environment (Operating system, version and so on): Win10
- .NET Framework version: .Net 6.0

I attached the font that I am using:
[Style Script.zip](https://github.com/SixLabors/Fonts/files/9525899/Style.Script.zip)

**Comment by JimBobSquarePants** [comment]
Can you please fill in the issue form properly specifying version numbers etc?

**Comment by Kizuto3** [comment]
I updated the issue form

**Comment by JimBobSquarePants** [comment]
Thanks!

**Comment by Kizuto3** [comment]
Thanks for fixing out of range exception!
However, a new issue appeared (steps to reproduce are the same). For some reasons glyphs are not generated for some letters: 'r' in 'enter' and 'h' in 'the'. Can you please take a look at this? 

![image](https://user-images.githubusercontent.com/38604580/195024630-5756bf15-da5b-4819-829a-829e14dffe79.png)

**Comment by Kizuto3** [comment]
That's OK, thank you!
