### ISSUE TITLE
Font Hinting 

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#30]
Provide a mechanism for processing the font hints.

**Comment by JimBobSquarePants** [comment]
Some further information. 

We should be able to port an implementation from https://github.com/LayoutFarm/Typography (MIT)

They use the following [HintTechnique ](https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Demo/Shared/GlyphPathBuilder/GlyphOutlineBuilderBase.cs#L169-L191)  enum to describe hinting.

Interpreting the hinting instructions appears to be handled by [TrueTypeInterpreter](https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Typography.OpenFont/TrueTypeInterperter/TrueTypeInterpreter.cs)

The underlying implementation of which is a port from [SharpFont](https://github.com/MikePopoloski/SharpFont/blob/b28555e8fae94c57f1b5ccd809cdd1260f0eb55f/SharpFont/Internal/Interpreter.cs)

**Comment by JimBobSquarePants** [comment]
Initial support for this has been implemented in #210 We still need to implement [hinting adjustments](https://github.com/SixLabors/Fonts/pull/210#issuecomment-934333756) for specific fonts a la FreeType and do optimizations.

**Comment by JimBobSquarePants** [comment]
@tocsoft Do you think we should close this now?

**Comment by tocsoft** [comment]
Yeah we probably should close this one as we have hinting now... I think anything else now should new issues/bugs rather than initial implementation.

The only thing we might still need to consider is if we should enable it by default or not. That decision probably requires a whole suite of samples being generated with a large variety of settings and fonts and comparing outputs. If at a significantly high percentage mark we decide we don't produce worse results and on average we generally produce better with it on rather than off then we should turn it on by default.. in one of the 2 modes anyway.

**Comment by JimBobSquarePants** [comment]
> If at a significantly high percentage mark we decide we don't produce worse results and on average we generally produce better with it on rather than off then we should turn it on by default.. in one of the 2 modes anyway.

Yeah. Good idea. I've been happy with the improvements I've seen following my recent changes but you never know.
