### ISSUE TITLE
MAUI.Android error: cant use FontCollection() add a  font stream

### ISSUE THREAD

**Issue by 3egirlsdream** [SixLabors/Fonts#324]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.0.0

### Other ImageSharp packages and versions

SixLabors.Fonts 1.0.0-beta19

### Environment (Operating system, version and so on)

MAUI Android

### .NET Framework version

.net 6

### Description

- using same code, it work well on windows 10. 
- and on Android will occur "maui special method not support" error.
- on Android the performance very bad, if image bigger a little,it will very slow.
- support MAUI?

### Steps to Reproduce

- create a demo maui app 
- remove the font file to root
- use those code
````
           SixLabors.Fonts.FontFamily? family = null;
            SixLabors.Fonts.FontFamily? familyBold = null;
            var stream = FileSystem.OpenAppPackageFileAsync("OpenSans-Regular.ttf").Result;
            var collection2 = new FontCollection();
            family = collection2.Add(stream);
````

### Images

````
            SixLabors.Fonts.FontFamily? family = null;
            var stream = FileSystem.OpenAppPackageFileAsync("OpenSans-Regular.ttf").Result;
            var collection2 = new FontCollection();
            family = collection2.Add(stream);
````

**Comment by JimBobSquarePants** [comment]
You should raise any MAUI specific issues with that repository. ImageSharp and Fonts use standard .NET components.

**Comment by 3egirlsdream** [comment]
> You should raise any MAUI specific issues with that repository. ImageSharp and Fonts use standard .NET APIs.

you can find bug by those steps:
- create template maui app (official template project), it include fonts file in 'Resources/Fonts/'
- move a font file to root
- run code
 ```` 
            var stream = FileSystem.OpenAppPackageFileAsync("OpenSans-Regular.ttf").Result;
            var collection = new FontCollection();
            var family = collection.Add(stream);
````
- u will find an exception with message "maui special method not support"
- platform：MAUI Android 13 Debug mode
- it's a bug or due to my error operation? or just not support good to maui?

**Comment by JimBobSquarePants** [comment]
You need to understand. If MAUI has constraint you need to confirm them with the team responsible. None of the APIs used in this codebase are subject to platform restrictions. I.E it should run anywhere the >NET runtime is installable.
