### ISSUE TITLE
Problem with wrapping long words

### ISSUE THREAD

**Issue by IshmaZX82** [SixLabors/Fonts#330]
### Description

Found a problem with the wrapping of long words.
In WinForms/Wpf/MS-Word, if a long word does not fit entirely into the output rectangle, it is split into parts.
In this library, long words are not broken into parts, they are displayed further outside the rectangle.
The textOptions.WordBreaking property does not help: BreakAll mode breaks all words, Standard mode does not break long words.

### Steps to Reproduce

```
var text1: "abcdefghijklmnopqrstuvwxyz"
var text2: "abcdefghijklmnopqrstuvwxyz \r\n abcdefghijklmnopqrstuvwxyz"
var text3: "abcdef ghijk lmnopq rstuvwxyz"
....
var textOptions = new SixLabors.Fonts.TextOptions(font);
textOptions.WrappingLength = layoutRectangle.Width;
textOptions.WordBreaking = SixLabors.Fonts.WordBreaking.BreakAll; //or Standard

canvasImage.AddDrawingOperation(DrawingOptions, (x, o) => x.DrawText(o, textOptions, text1, brush, null));
```
Results:
![problem](https://user-images.githubusercontent.com/52139455/236144743-6942314e-763d-48de-b17d-2b86bcd8cb86.png)

Of course, I can write my big method using TryMeasureCharacterBounds, which will determine where the line goes outside the rectangle and break it. But I would like an easier and faster way.

### System Configuration

Fonts version: current source code
Other Six Labors packages and versions: none
Environment (Operating system, version and so on): Win10
.NET Framework version: .Net 6.0

**Comment by IshmaZX82** [comment]
WinForms/Wpf/MS-Word use a behavior that is closest to "word-break: break-word".
https://jsfiddle.net/7sf960yj/1/

Any chance to add this type of wordwrap?

**Comment by JimBobSquarePants** [comment]
Just gave it a first pass run. Looks promising with very few changes. Will have to test further though to ensure I haven't broken anything.

![abcdefghijklmnopqrstuvwxyz](https://user-images.githubusercontent.com/385879/236626793-d9fe8160-0079-4fee-9bc1-3722f9f64957.png)
![abcdefghijklmnopqrstuvwxyz--abcdefghijklmnopqrstuvwxyz](https://user-images.githubusercontent.com/385879/236626791-88928cc5-3fd9-47a3-bc5c-a90c3cb74a8f.png)
![abcdef ghijk lmnopq rstuvwxyz](https://user-images.githubusercontent.com/385879/236626792-84fe72c5-0e7e-471b-b78b-1ab3d09b5995.png)
