### ISSUE TITLE
Problem with font "Sumana", wrong left parenthesis character

### ISSUE THREAD

**Issue by IshmaZX82** [SixLabors/Fonts#334]
### Description

When using the font "Sumana", the left parenthesis character is not displayed correctly.
The problem is with both the bold and the regular version of the font.
![image](https://github.com/SixLabors/Fonts/assets/52139455/b2b067de-89bc-4b6c-9ad6-2b3e3fd16e82)

### Steps to Reproduce

To reproduce the problem, you need to display the text with a bracket in any way, for example:
"0(1)2"

Font file:
[Sumana.zip](https://github.com/SixLabors/Fonts/files/11625048/Sumana.zip)

The font was downloaded from here:
https://fonts.google.com/specimen/Sumana

### System Configuration

- Win10 Pro
- Net6 project
- SixLabors.Fonts v1.0.0-beta19 package

**Comment by JimBobSquarePants** [comment]
Looks like some form of faulty substitution. Have you spotted anything during debugging?

**Comment by IshmaZX82** [comment]
> Have you spotted anything during debugging?

No, there were no exceptions.
I checked the font with FontValidator, the font contains many errors and warnings.
But System.Drawing displays it correctly.
