### ISSUE TITLE
TextMeasurer.Measure returns incorrect width

### ISSUE THREAD

**Issue by Bykiev** [SixLabors/Fonts#345]
### Description
`TextMeasurer.Measure` returns width 8px for character with font Calibri 11px with 96 DPI, but it should be 7px

### Steps to Reproduce
```
SixLabors.Fonts.FontFamily fontFamily;
SystemFonts.TryGet("Calibri", CultureInfo.CurrentCulture, out fontFamily);

Font font = fontFamily.CreateFont(11, FontStyle.Regular);
var rec = TextMeasurer.Measure(new string('0', 1), new TextOptions(font) { Dpi = 96 });
Console.WriteLine(rec.Width);
```

### System Configuration
SixLabors.Fonts latest version, OS Windows

**Comment by Bykiev** [comment]
I've tested with the master branch and it return 7 now, seems the issue was already fixed

**Comment by JimBobSquarePants** [comment]
Master (and the latest nightly packages) provide 3 types of measurement. Bounds, size, and advance for both strings and individual characters. Previously only bounds and advance were available.

Be aware that System.Drawing should not be used as a control as it is actually horribly inconsistent. For example https://stackoverflow.com/questions/1203087/why-is-graphics-measurestring-returning-a-higher-than-expected-number

Fonts, instead, matches browser output for all measurements.
