### ISSUE TITLE
Wrong character orientation when drawing brackets

### ISSUE THREAD

**Issue by Hellobaka** [SixLabors/Fonts#355]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Wrong character orientation when drawing brackets. Characters should be like this`【】「」`.
But drawing with code, they become like this.
![image](https://github.com/SixLabors/ImageSharp.Drawing/assets/50934714/8995f43a-8f2b-4f35-a2b9-9a42349c64bf)

I have tried 1.0.0-beta15. This version can work properly.
![image](https://github.com/SixLabors/ImageSharp.Drawing/assets/50934714/0899a329-a89d-4e1a-a5c5-fdac305a6002)

### Steps to Reproduce
```csharp
Image<Rgba32> img = new(200, 100);
Font font = SystemFonts.CreateFont("Microsoft YaHei", 15);
img.Mutate(x => x.DrawText("()【】「」", font, Color.Black, new PointF(10, 10)));

img.Save("1.png");
```
### System Configuration
- ImageSharp.Drawing version: 1.0.0
- Other ImageSharp packages and versions: 
    - SixLabors.ImageSharp - 2.1.6
- Environment (Operating system, version and so on):
    - OS: Windows11 22H2
- .NET version: .Net 7
- Additional information: 1.0.0-beta15 does not have this problem

**Comment by JimBobSquarePants** [comment]
Updating to SixLabors.Fonts v1.0.1 will fix the issue

**Comment by Hellobaka** [comment]
> Updating to SixLabors.Fonts v1.0.1 will fix the issue

Thank You!
