### ISSUE TITLE
Any tab after the third in a line doesn't get rendered

### ISSUE THREAD

**Issue by TodesBrot** [SixLabors/Fonts#36]
When rendering a string that contains more than 3 tabs, only the first 3 are rendered. I haven't found out completely how it works yet, but that seems to be the general gist of it. The easiest way to reproduce the bug is comparing how the strings "\t\t\tx" and "\t\t\t\tx" get rendered.

**Comment by tocsoft** [comment]
I can't reproduce this in my tests, can you try again me for with the latest release.

**Comment by TodesBrot** [comment]
I can't render any text in the latest release, as Image.DrawText references the FontSpan class, which doesn't seem to exist in the latest release. I have updated all packages to the latest release.

**Comment by tocsoft** [comment]
Bugger I forget about those changes... you'll want to revert to the previous alpha for now, the latest one needs https://github.com/JimBobSquarePants/ImageSharp/pull/253 to land in the imagesharp repo before you can use it with imagesharp.drawing.

Yeah `FontSpan` got renamed to `RendererOptions` as a more accurate name.

**Comment by TodesBrot** [comment]
I updated everything to the newest version and this bug seems to be fixed. Much appreciated!
