### ISSUE TITLE
Inter Variable rendering incorrectly

### ISSUE THREAD

**Issue by sowa705** [SixLabors/Fonts#369]
Hi, i'm trying to render text with the https://rsms.me/inter/ font but the result is not correct.

```
var fontFamily = fontCollection.Get("Inter Variable");
var font = fontFamily.CreateFont(96, FontStyle.Regular);

var img = new Image<Rgba32>(1960, 180, Rgba32.ParseHex("#FF0000FF"));
img.Mutate(g => {
    var textFont = font;
    var paths = TextBuilder.GenerateGlyphs("Inter variable", new TextOptions(textFont) {
        Origin = new Vector2(980, 90),
        VerticalAlignment = VerticalAlignment.Center,
        HorizontalAlignment = HorizontalAlignment.Center,
        TextAlignment = TextAlignment.Center,
        Font = textFont
    });
    g.Fill(Color.Black, paths);
});

img.Save("test.png");
```

Resulting image

![test](https://github.com/SixLabors/Fonts/assets/25490036/a4fb6f64-84a1-4c85-82c7-8d44a6b2fddc)

Test environment
```
SixLabors.Fonts Version="2.0.1"
SixLabors.ImageSharp Version="3.1.1"
SixLabors.ImageSharp.Drawing Version="2.1.0"
OS: Windows 11 x64
Runtime: .NET 8.0.100
```

**Comment by JimBobSquarePants** [comment]
Duplicate of https://github.com/SixLabors/Fonts/issues/5

Do not

**Comment by tocsoft** [comment]
I don't think that's not a bug, the issue is that fonts expect to be rendered with the NoneZero Intersection Rule (which our drawText apis do for you) but the `Fill` api defaults to the EvenOdd Intersection Rule rule for rasterization.

**Comment by tocsoft** [comment]
FYI the `DrawText` APIs will be more efficient (at least for larger pieces text) you should generally only use the `TextBuilder.GenerateGlyphs()` path building base APIs if you need to transform/mutate vectors themselves.

**Comment by JimBobSquarePants** [comment]
Thanks @tocsoft !

**Comment by sowa705** [comment]
Thanks for help and explanation

**Comment by SpaceCheetah** [comment]
Is there a way to detect when a font needs NonZero or not, without visually looking at it? Surely there is somewhere, but I'm not seeing where DrawText deals with that (and for my situation I need transformations at the glyph level).

**Comment by SpaceCheetah** [comment]
On closer inspection, it looks like buried deep in RichTextGlyphRenderer it always uses NonZero, unless I'm reading something wrong. Is that just always correct?

**Comment by JimBobSquarePants** [comment]
Yeah TrueType and CFF fonts always use NonZero
