### ISSUE TITLE
Problem with TextMeasurer

### ISSUE THREAD

**Issue by SzymonParol** [SixLabors/Fonts#416]
### Discussed in https://github.com/SixLabors/Fonts/discussions/415

<div type='discussions-op-text'>

<sup>Originally posted by **SzymonParol** October 22, 2024</sup>
I am getting an exception with the Noto Sans font, while other fonts work fine. Is it a fault of the font, or is there some other problem? Can you help me?

I downloaded the font from: https://fonts.google.com/noto/specimen/Noto+Sans.

I tried to measure text using the following code:

using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Drawing.Processing;

using SixLabors.ImageSharp.Formats.Jpeg;
using System.Data;
using System.Xml.Linq;
using System.Text.RegularExpressions;

// Part of code
FontData = LoadFontFromResources(FontHeight);
var textOptions = new TextOptions(FontData);
var size = TextMeasurer.MeasureSize("Any content", textOptions); // Exception is thrown here

private static Font LoadFontFromResources(float size)
{
    FontCollection collection = new();
    FontFamily family = collection.Add(@$"{AppDomain.CurrentDomain.BaseDirectory}\Resources\NotoSans-Regular.ttf");
    Font font = family.CreateFont(size, FontStyle.Regular);
    return new(font, FontHeight, FontStyle.Regular);
}

I am getting the following exception:

SixLabors.Fonts.InvalidFontFileException
HResult=0x80131500
Message=anchorFormat identifier 273 is invalid. Should be '1', '2', or '3'.
Source=SixLabors.Fonts
...</div>

**Comment by JimBobSquarePants** [comment]
Please create a new issue using the issue template and I’ll have a look.

**Comment by SzymonParol** [comment]
> Please create a new issue using the issue template and I’ll have a look.

Hi,

I don’t have the option to create an issue based on the oss-bug-report.md file. The only options available are "Ask a Question" and "Feature Request." Could you please let me know what I should do in this case? Sorry for any inconvenience caused.

**Comment by JimBobSquarePants** [comment]
GitHub must have changed something. I’ll fix it soon

**Comment by JimBobSquarePants** [comment]
@SzymonParol Fixed now. Sorry for the confusion.

**Comment by JimBobSquarePants** [comment]
Closed in favor of #417
