### ISSUE TITLE
Scaled Word Wrap

### ISSUE THREAD

**Issue by dotnetnoobie** [SixLabors/Fonts#42]
```
var style = new FontSpan(f, 72) { WrappingWidth = targetWidth };
s = measurer.MeasureText(text, style);
```

This is the code from the example you gave before for doing "Scaled Word Wrap"
but this no longer works in the latest versions 

Is there a new way to achieve the same as above?

Previous issue where you gave the example code
[layout wrapping support #4](https://github.com/SixLabors/Fonts/issues/4)

**Comment by tocsoft** [comment]
@dotnetnoobie `FontSpan` got renamed to `RendererOptions`
