### ISSUE TITLE
Could not install package - SixLabors.Fonts 2.0.6

### ISSUE THREAD

**Issue by AndrewRDale** [SixLabors/Fonts#421]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Fonts
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Fonts version

SixLabors.Fonts 2.0.6

### Other Six Labors packages and versions

SixLabors.Fonts 2.0.6

### Environment (Operating system, version and so on)

Windows 10, Visual Studio 2022, VB.NET

### .NET Framework version

v4.8.1

### Description

Windows 10, Visual Studio 2022, VB.NET, 

NuGet Package installer is suggesting I upgrade SixLabors.Fonts but I keep getting this message when I try.

Could not install package 'SixLabors.Fonts 2.0.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Should I be trying to install this Update?
Which is the latest stable update that supports .NETFramework,Version=v4.8.1

### Steps to Reproduce

Load project targeting  .NETFramework,Version=v4.8.1
Open NuGet Package installer in VS 2022
Updates - SixLabors.Fonts 2.0.6 is suggested
Install

**Comment by tocsoft** [comment]
SixLabors.Fonts 2.0.6 is only compatible with .net 6.0+

Support for full framework was dropped as part of releasing v2.
