### ISSUE TITLE
Text run incorrectly applied inclusively to final letter when End points to final letter of text string

### ISSUE THREAD

**Issue by jez9999** [SixLabors/Fonts#427]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.6

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Drawing 2.1.4

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 9

### Description

When using `TextRuns` to apply different formatting to different parts of text in `DrawText`, ImageSharp appears to incorrectly include the final character of the input text in a text run if the text run's `End` points to the final letter of the text string (it is supposed to be exclusive, so the letter pointed to should *not* be formatted by that text run).  A minimal reproduction is given below.  It's a C# console program with classes `FontManager` and `Program`.

### Steps to Reproduce

**FontManager.cs**
```
using SixLabors.Fonts;

namespace TextRunTest;

internal class FontManager {
    public FontManager() {
        _allFontsCollection = new FontCollection();
        _allFontsCollection.AddSystemFonts();
    }

    private readonly FontCollection _allFontsCollection;
    private readonly Dictionary<(string FontName, float FontSize, FontStyle FontStyle), Font> _cachedFonts = [];

    public Font GetFont(string fontName, float fontSize, FontStyle fontStyle) {
        var key = (fontName, fontSize, fontStyle);

        if (!_cachedFonts.ContainsKey(key)) {
            _cachedFonts[key] = _allFontsCollection.Get(fontName).CreateFont(fontSize, fontStyle);
        }
        return _cachedFonts[key];
    }
}
```

**Program.cs**
```
using System.Numerics;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.Fonts;

namespace TextRunTest;

internal class Program {
    static void Main(string[] args) {
        Console.WriteLine("Rendering test images...");

        var fontManager = new FontManager();

        Image imgTest = new Image<Rgba32>(300, 200, Color.White);
        imgTest.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 80, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    TextRuns = [
                        new() {
                            Font = fontManager.GetFont("Arial", 80, FontStyle.Italic),
                            Start = 1,
                            End = 4
                        }
                    ]
                },
                "linell",
                Color.Black
            )
        );
        imgTest.SaveAsPng("c:/development/diff/testImg1.png");
        // ^ correct, italicized: linell
        //                         ---

        Image imgTest2 = new Image<Rgba32>(300, 200, Color.White);
        imgTest2.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 80, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    TextRuns = [
                        new() {
                            Font = fontManager.GetFont("Arial", 80, FontStyle.Italic),
                            Start = 1,
                            End = 5
                        }
                    ]
                },
                "linell",
                Color.Black
            )
        );
        imgTest2.SaveAsPng("c:/development/diff/testImg2.png");
        // ^ incorrect, italicized: linell
        //                           -----

        Console.WriteLine("Done.");
    }
}
```

### Images

![testImg1](https://github.com/user-attachments/assets/5c8da28b-5442-4ba4-b8a1-2a5344f97755)
![testImg2](https://github.com/user-attachments/assets/8d53b299-cfbe-4b84-a6c4-e59406f3bea8)

**Comment by JimBobSquarePants** [comment]
P.S please ensure you dispose of your images.

**Comment by jez9999** [comment]
> P.S please ensure you dispose of your images.

Yeah, I've noticed a few places where I wasn't doing that.

It's a bit of a shame ImageSharp has `IDisposable` classes.  One of the nice things about C# was not having to worry about cleanup like you would in C++ and it was quite rare things that accessed system resources that did require it.  It's nice not to have it precisely because it's so easy to forget.  As ImageSharp is entirely managed code as far as I'm aware and `Image` is all memory stuff it seems like it should be doable without requiring explicit disposal.

**Comment by JimBobSquarePants** [comment]
It’s a misconception that `IDisposable` is rare in C#, but it’s actually used extensively, even in core .NET libraries. Anything involving streams, file IO, database connections, or even timers relies on `IDisposable` to manage resources. The reality is that while C# abstracts a lot, explicit cleanup is still necessary when dealing with finite resources, whether managed or unmanaged.

In ImageSharp’s case, we use unmanaged memory for performance reasons. Managed arrays are subject to garbage collection, and allocating large blocks frequently (as you would in image processing) can cause significant GC pressure and pauses. By leveraging unmanaged memory, we avoid this overhead, but it means we need to ensure proper cleanup to prevent memory leaks. Without this approach, performance would suffer dramatically in real-world use cases.

**Comment by jez9999** [comment]
Yes.  I end up with a lot of `using` noise in my code, though.  Perhaps there would be some better design to explicitly clean up resources.  And you also have the confusion now of things like `Task` that are completely unnecessary to dispose, so it's hard to know what to dispose.

**Comment by JimBobSquarePants** [comment]
The `using` pattern might feel noisy, but it’s there for a reason - deterministic cleanup is critical for managing resources properly. It’s not a design flaw; it’s an intentional part of .NET for anything that holds onto finite resources and it's ubiquitous. 

You wouldn't dispose of a `Task`, rather any result it yields. Knowing which types to dispose eventually becomes second nature based on the context of what the code is doing, however this may help you to learn. https://github.com/DotNetAnalyzers/IDisposableAnalyzers

**Comment by JimBobSquarePants** [comment]
Sorry I should have been more clear. While `Task` implements `IDisposable` for edge cases where disposing can reduce memory pressure (e.g., with long-lived or high-throughput task usage), for the vast majority of scenarios, relying on garbage collection is sufficient. Requiring routine disposal of tasks would add unnecessary complexity to asynchronous programming.

`Task` implementing `IDisposable` _could_ be considered a leaky abstraction because it exposes implementation details that most developers shouldn’t need to worry about, violating the expectations set by `IDisposable`. However, this is a pragmatic design choice aimed at balancing ease of use and performance in common scenarios.

An `IOptionalDisposable` alternative wouldn’t be viable because it lacks determinism
