### ISSUE TITLE
Method not found.

### ISSUE THREAD

**Issue by TurboLOL** [SixLabors/Fonts#43]
So I am doing image.DrawText();
and I get this exception from some reason,
Exception: Method not found: 'Void SixLabors.Fonts.IGlyphRenderer.BeginGlyph(SixLabors.Primitives.RectangleF)'.

I used breakpoints and it runs fine until DrawText(). I am not sure how I would solve this issue.

**Comment by tocsoft** [comment]
Looks like your SixLabors.Shapes.Text dependency needs updating.

**Comment by TurboLOL** [comment]
Thank you very much. It fixed it.
