### ISSUE TITLE
Unnecessary text wrap when newline separates words instead of space

### ISSUE THREAD

**Issue by jez9999** [SixLabors/Fonts#431]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Fonts
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Fonts version

2.0.6

### Other Six Labors packages and versions

SixLabors.ImageSharp 3.1.6, SixLabors.ImageSharp.Drawing 2.1.4

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 9

### Description

When using `DrawText`, text is unnecessarily given a newline through text wrapping (ie. nothing is then rendered on the new line) when a newline character is used to separate two words rather than a space.

### Steps to Reproduce

```
internal class Program {
    static void Main(string[] args) {
        Console.WriteLine("Rendering test images...");

        var fontManager = new FontManager();

        Image imgTest1 = new Image<Rgba32>(550, 350, Color.White);
        imgTest1.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 60, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    WrappingLength = 400,
                },
                "- Lorem ipsullll dolor sit amet\n-consectetur elit",
                Color.Black
            )
        );
        imgTest1.SaveAsPng("c:/development/diff/testImg1.png");
        // ^ correct

        Image imgTest2 = new Image<Rgba32>(550, 350, Color.White);
        imgTest2.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 60, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    WrappingLength = 400,
                },
                "- Lorem ipsulll\ndolor sit amet\n-consectetur elit",
                Color.Black
            )
        );
        imgTest2.SaveAsPng("c:/development/diff/testImg2.png");
        // ^ correct, no wrapping yet

        Image imgTest3 = new Image<Rgba32>(550, 350, Color.White);
        imgTest3.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 60, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    WrappingLength = 400,
                },
                "- Lorem ipsullll\ndolor sit amet\n-consectetur elit",
                Color.Black
            )
        );
        imgTest3.SaveAsPng("c:/development/diff/testImg3.png");
        // ^ incorrect, extra newline after: - Lorem ipsullll

        Console.WriteLine("Done.");
    }
}
```

### Images

![testImg1](https://github.com/user-attachments/assets/de5dcc52-c4b8-4f1d-bc3e-73e21dc78df3)
![testImg2](https://github.com/user-attachments/assets/199e14f1-d69d-4fb8-b50b-f4f63e652dc2)
![testImg3](https://github.com/user-attachments/assets/16fd6626-cbb5-4745-82c7-59d0f9a159c7)

**Comment by JimBobSquarePants** [comment]
I'm working on this. It's taking a complete rewrite of the line breaking algorithm code so could be a few days.
