### ISSUE TITLE
fonts.Install return font family instead of font

### ISSUE THREAD

**Issue by djpeace** [SixLabors/Fonts#46]
`FontCollection fonts = new FontCollection();`
`Font font1 = fonts.Install("./path/to/font1.ttf");`
`Font font2 = fonts.Install("./path/to/font2.woff");`

I cant get the sample code working.

**Comment by tocsoft** [comment]
that's correct `fonts.Install(..)` returns a `FontFamily` not a `Font`. 

Which sample code are you talking about? all the samples in `samples` directory all show `FontCollection.Install()` returning a `FontFamily`.

To get a `Font` from a `FontFamily` you can either use the `CreateFont()` extension method on `FontFamily`  or by passing the `FontFamily` using the `Font` classes constructor.

**Comment by tocsoft** [comment]
woops... thanks for pointing that out, totally failed to spot that one 👍

**Comment by djpeace** [comment]
No problem.

**Comment by djpeace** [comment]
Issue resolved.
