### ISSUE TITLE
Wrapped text should not include space at start of new line

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#47]
_originally posted by @CDDelta at  SixLabors/ImageSharp#375_

### Description

When wrapping text with spaces to a new line DrawText() starts the next line with a space.

### Steps to Reproduce

Draw text (eg. "TEST TEST TEST TEST") that includes spaces and enable wrapping.
Output and view it.
Here is an example I made.
![output_512x512](https://user-images.githubusercontent.com/14818946/32054458-2aba9c08-baaa-11e7-8c15-2c89420aefa7.jpeg)

**Comment by CDDelta** [comment]
Interestingly this bug does not occur when text is centre or right aligned.
