### ISSUE TITLE
Feature Request: Expose font glyphs, geometry, etc

### ISSUE THREAD

**Issue by vpenades** [SixLabors/Fonts#57]
Although the main focus of SixLabors.Fonts is to provide font rendering features to ImageSharp, I don't see why it can't be used for much more than that.

So I would like to request to expose glyph information such as:
- Glyph Metrics
- Glyph Geometry

Glyph metrics are required in case you want to create a texture font atlas, as used by game engines, where each letter is rendered into the texture, and the corresponding glyph metadata is stored in a separate file, so the engine can use it to render text on its own.

Glyph geometry (both raw and triangulated) can be used for vector graphics, or rendering large form factor text in videogames.

**Comment by tocsoft** [comment]
As a work around for you you can use the `SixLabors.Shapes.Text` package to render the text to Vectors which you can transform/interrogate as required.

**Comment by woutware** [comment]
We need access to the font em size, ascent, descent, and line spacing, analogous to methods `int System.Drawing.FontFamily.GetEmHeight(System.Drawing.FontStyle)`, `int System.Drawing.FontFamily.GetCellAscent(System.Drawing.FontStyle)`, `int System.Drawing.FontFamily.GetCellDescent(System.Drawing.FontStyle)`, `int System.Drawing.FontFamily.GetLineSpacing(System.Drawing.FontStyle)`.

The use case is to do our own text layout based on these metrics to mimic AutoCAD's text rendering, which deviates slightly from the raw true type font metrics, but we use these metrics as a starting point, which is then slightly modified.

**Comment by tocsoft** [comment]
This can/should be done by newing up a `Font` instance (as this represents a styled font)

we already expose [EmSize](https://github.com/SixLabors/Fonts/blob/16f933e014cd62f5e593132fba6268b710629551/src/SixLabors.Fonts/Font.cs#L117), and with only a single small addition of `public int LineHeight => this.instance.Value.LineHeight;` can expose the line height. 

we should just need to expand https://github.com/SixLabors/Fonts/blob/master/src/SixLabors.Fonts/FontInstance.cs and https://github.com/SixLabors/Fonts/blob/master/src/SixLabors.Fonts/IFontInstance.cs to expose the final 2 values and should be simple enough.

**Comment by woutware** [comment]
https://github.com/SixLabors/Fonts/pull/63

**Comment by JimBobSquarePants** [comment]
Fixed by #63 and #102
