### ISSUE TITLE
Support word breaking

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#60]
Add a flag to `RenderOptions` to turn on word breaking.

wher word breaking is the ability to cut words in half at word wrapping boundries.

**Comment by JimBobSquarePants** [comment]
@tocsoft How do you envisage this property? A simple boolean or something more. 

Now we enumerate graphemes within `TextLayout` and have all the break info this should be ok to implement.

**Comment by tocsoft** [comment]
didn't have a clear idea on how this would be exposed really... i guess it would all depends on if we also wanted to append hyphens (or language specific equivalent) on word breaking and how we want that characters to be fed in.

it could be a simple as 2 new properties, `WordBreaking` = `none` | `auto` (enum to allow for fine tuned rule in the future if/when we need to support special cases around  Chinese/Japanese/Korean text) and `HyphenCharacter` to allow switching out the character to use when word breaking (allows for setting it to null to mean do not insert character at all) could also be a string instead of a `Nullable<char>` to allow for multiple chars at once? or empty for when not wanted at all.

**Comment by JimBobSquarePants** [comment]
`WordBreaking = none | auto` should be simple enough and a simple prototype seems to be working well.

Got a circular dependency thing going on just now though where there property type needs to exist in Drawing before I can do some rendering tests.

**Comment by JimBobSquarePants** [comment]
@tocsoft Are you ok with this behavior?

Simply applying `WordBreaking.Auto` with a `WrappingWidth` will look for a break opportunity at the beginning of each grapheme and will never break within a grapheme. Basically the same as CSS `word-break : break-all`

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

This means Chinese/Japanese/Korean should never break, nor should combined emojis (_though it looks like we cannot render those yet_)

![THISIS~1](https://user-images.githubusercontent.com/385879/130566596-3c17052f-2119-4bd3-affb-51fee2e8af93.PNG)

**Comment by tocsoft** [comment]
looks good to me... the combined emoji will probably be a ligature thing which is an area we are still missing.

Looks like you are still missing the hyphen from your example image... that might/will probably make wrapping slightly more difficult as we will need to take into account of the width of the hyphen when the break lands with-in a word.

**Comment by JimBobSquarePants** [comment]
Ace… I haven’t done anything with hyphens yet. I’m considering using a different property similar to CSS hyphens 

https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

**Comment by JimBobSquarePants** [comment]
>the combined emoji will probably be a ligature thing which is an area we are still missing

We should use LayoutFarm.Typography as inspiration for that feature. They have great support.
