### ISSUE TITLE
Add overloads what we except a string to accept `ReadonlySpan<char>`

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#64]
update api to allow processing `ReadonlySpan<char>` to avoid unnecessary string allocations. 

will then be able to allow consumers of ImageSharp to draw text with out the additional string allocations.

**Comment by iamcarbon** [comment]
There's an implicit conversion from string to ReadOnlySpan<char>. What do you think of just changing the type of the existing methods? This should be a non-breaking change as long as the consumer recompiles. 

I've prototyped this in the latest PR.

**Comment by iamcarbon** [comment]
Included this in the latest PR.

**Comment by JimBobSquarePants** [comment]
Looks like we can close this then. Thanks @iamcarbon
