### ISSUE TITLE
Make FontInstance public

### ISSUE THREAD

**Issue by tzachshabtay** [SixLabors/Fonts#65]
Currently FontInstance is internal, meaning I can't call the LoatFont variants from my code and I'm forced to use FontCollection.
However FontCollection is not a useful abstraction for me: it first loads the font from the stream and then checks if the family name already exists.
I know better in my code and have my own caching to prevent loading the font from the stream in the first place (using file name or embedded resource id as the key) if it's already loaded so I don't need FontCollection and it just adds overhead with those dictionary checks and the lock: https://github.com/SixLabors/Fonts/blob/4ee628bad5c0206440bd6cc865ee3d6a3285c329/src/SixLabors.Fonts/FontCollection.cs#L105

Making FontInstance public would allow me to implement my own caching without those overheads.

**Comment by JimBobSquarePants** [comment]
Fixed by #102
