### ISSUE TITLE
Support for RTL text

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#66]
Add option to text layout engine to support rendering 'right to left' instead of the current 'left to right'.

This will require new option on `RendererOptions` to allow configuring 'right to left` 
and updating https://github.com/SixLabors/Fonts/blob/4ee628bad5c0206440bd6cc865ee3d6a3285c329/src/SixLabors.Fonts/TextLayout.cs#L25 to layout the characters in the corrent 'right to left' style.

**Comment by JimBobSquarePants** [comment]
While I've added a Bidi implementation in #160 I'm really not happy with the shape of the API it brings. 

I want to investigate this alternative.
https://github.com/Tehreer/SheenBidi

[LayoutFarm Typography](https://github.com/LayoutFarm/Typography) is currently using a C# version that appears to be based on https://archive.codeplex.com/?p=sheenbidi written by the same author as the C version.
