### ISSUE TITLE
Use int for character representation to support full Unicode

### ISSUE THREAD

**Issue by Jjagg** [SixLabors/Fonts#69]
To support the full Unicode range, the character representation should map to a Unicode codepoint which is 32-bit. Currently `char` is used. This is important to support characters that require 4 bytes in UTF-16 like emoji. I have a branch in my fork where I changed the internal representation to UTF-32 (by using `int` everywhere instead of `char`), so I can set up a PR if that's all right :) 
https://github.com/Jjagg/Fonts/commit/4c058ec9015159b46f941375c84a9b948de234db?w=1

The only change in functionality is [in TextLayout.cs](https://github.com/Jjagg/Fonts/commit/4c058ec9015159b46f941375c84a9b948de234db?w=1#diff-639d75ec476371a1d815b832ea3ffec9R76) to keep it easy to review. For 2-byte UTF-16 characters nothing changed functionally at all.

**Comment by Jjagg** [comment]
I say 'Unicode code point' in the docs, but 'UTF-32 encoded character' would actually be more apt.

**Comment by tocsoft** [comment]
that's awesome 😄 please send in a PR and i'll get it merged in.

**Comment by Jjagg** [comment]
@tocsoft Thanks for the quick response :) PR is up! #70
