### ISSUE TITLE
Inspiration for supporting more of the TTF spec

### ISSUE THREAD

**Issue by roy-t** [SixLabors/Fonts#73]
A while ago I checked out this repository but it didn't support everything I needed. So I made my own library for reading the specific parts of TTF files that I need. Sometimes its quite hard to understand the TTF spec so I want to share what I've learned as much as possible.

So feel free to take anything from my TTF library to make your (much more complete) library better :D 

https://github.com/roy-t/TrueType

For example, one of the things that is nice to have a look at the files that map MAC and Windows language codes to CultureInfo. I also think I support more CMAP formats.

**Comment by dlemstra** [comment]
You are more than welcome to help us out by opening pull requests to integrate your changes.

**Comment by JimBobSquarePants** [comment]
I think we support way more stuff now than the referenced project now so am going to close this. Any specific missing features can be added as individual tickets.
