### ISSUE TITLE
Generalize FileFontInstance to not be restricted to file based fonts.

### ISSUE THREAD

**Issue by woutware** [SixLabors/Fonts#74]
FileFontInstance is currently restricted to file based fonts. To enable lazy loading from for example embedded resources, or downloaded from the internet I propose to change the constructor parameter from `string filename` to `Func<Stream> openStream`, so the caller can determine what kind of stream is opened.

A more appropriate name after this refactoring would be `LazyFontInstance`.

**Comment by JimBobSquarePants** [comment]
`FileFontInstance` is an internal type. We use `FontCollection` as the public type for loading fonts which supports both string paths and streams.
