### ISSUE TITLE
cmap table doesn't support 32-bit characters yet

### ISSUE THREAD

**Issue by lostllama** [SixLabors/Fonts#80]
Is this an ImageSharp issue?

If it is, is there an ETA for when such support will be added?

Sample string: 日本語

--
P.S. I'm using the beta 5 NuGet package.

**Comment by tocsoft** [comment]
sorry no eta i've added an issue to track adding the required functionality to enable this to work.

We should actually change this to not error when finding glyphs it can process and instead return the the empty glyph instead.

**Comment by zhangbendong** [comment]
@tocsoft    I met the same problem when I use some Chinese character in beta5. I don't know how to fix it.

Such as: 静蕾

Exception:
Unhandled Exception: SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using DelegateProcessor`1. See the inner exception for more detail. ---> System.NotImplementedException: cmap table doesn't support 32-bit characters yet.
   at SixLabors.Fonts.FontInstance.GetGlyphIndex(Int32 codePoint)
   at SixLabors.Fonts.FontInstance.SixLabors.Fonts.IFontInstance.GetGlyph(Int32 codePoint)
   at SixLabors.Fonts.TextLayout.GenerateLayout(String text, RendererOptions options)
   at SixLabors.Fonts.TextMeasurer.TextMeasurerInt.Measure(String text, RendererOptions options)

**Comment by microchi** [comment]
You can using [fix-glyphrendererparameters branch](https://github.com/SixLabors/Fonts/tree/js/fix-glyphrendererparameters) bypass this issue temporarily. I try to use the word "あなたの日本語 静蕾" with "msjhbd.ttf". There is no problem.  There are maybe some side effect inside.

**Comment by JimBobSquarePants** [comment]
@tocsoft What's different in that branch?

**Comment by microchi** [comment]
@JimBobSquarePants It's stopping throwing on large codepoints. You can see [the commit](https://github.com/SixLabors/Fonts/commit/5df8fab8a9e3d784797b1a420652c5916ffaab2a)
