### ISSUE TITLE
Uneven height of letters when text is wrapped

### ISSUE THREAD

**Issue by OutOfTeaException** [SixLabors/Fonts#81]
I tried to render some text using the font "Libertine". Unfortunately the letters are sometimes not aligned correctly. They are getting rendered a bit too high (I marked the spots):

![test_55](https://user-images.githubusercontent.com/4719501/43996120-494ba72a-9dbc-11e8-834d-d5f6d2030fb0.png)

Used Font: http://libertine-fonts.org/show-me/ (Download: https://sourceforge.net/projects/linuxlibertine/files/)

### What I already tried:
- The errors persists with different font sizes. Sometimes there a more affected letters, sometimes less.
- Rending the text using _WrapTextWidth = 0_ and an image with of 6000 in one big line the errors do not occur
- Drawing the same text with the same font using .NET Framework GDI+ API's is fine
- System fonts like _Arial_ and _Times new Roman_ get rendered correctly

### Code to reproduce:

```csharp
    const string text = "Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins Wilkins";
    
    var fontCollection = new FontCollection();
    var fontFamily = fontCollection.Install("LinLibertine_RZah.ttf");
    var font = fontFamily.CreateFont(55);
    
    var textGraphicOptions = new TextGraphicsOptions(true)
    {
    	HorizontalAlignment = HorizontalAlignment.Left,
    	VerticalAlignment = VerticalAlignment.Top,
    	WrapTextWidth = 500
    };
    
    using (var image = new Image<Rgba32>(600, 800))
    {
    	image.Mutate(ctx => ctx
    	   .Fill(Rgba32.White) // white background
    	   .DrawText(textGraphicOptions, text, font, Rgba32.Gray, new PointF(0,0)));    
    
    	image.Save("test.png");
    }
```
### System:
OS: Windows 10
.NET Core: 2.1

Used Libraries:
- SixLabors.ImageSharp.Drawing (1.0.0-beta0005) via nuget
  - Fonts (1.0.0-beta0007)
  - ImageSharp (1.0.0-beta0005)
  - Shapes (1.0.0-beta0007)

Perhaps there is something "wrong" with the font? Although using GDI+ it renders just fine. Maybe someone can investigte. Thanks!

**Comment by tocsoft** [comment]
this should now be fixed in the latest nightlies of `Sixlabors.ImageSharp`
