### ISSUE TITLE
Add support of parsing an loading Format 12 cmap subtables to allow for 32bit character glyphs

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#82]
We need to add a new subtable class in the same mannor as Format0 and Format4 subtabes (see here https://github.com/SixLabors/Fonts/tree/410375e740ec755ca848d1b6b5e3f7531aac429b/src/SixLabors.Fonts/Tables/General/CMap) 

Details for the subtable format can be found here https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-8-mixed-16-bit-and-32-bit-coverage

This will allow us to support wider glyph like those found in #80

**Comment by Tylertron1998** [comment]
Any update here? I believe this is what is currently holding me back from rendering emojis. On the linked issue someone had commented removing the throw point allows for Chinese characters to be rendered - but emojis are not, as I tried anyway.
