### ISSUE TITLE
Improve cross platform support for loading fonts

### ISSUE THREAD

**Issue by PS-StuartZahn** [SixLabors/Fonts#85]
Provide a cross-platform approach to fill the FontCollection with system fonts. 

The current logic doesn't work in OSX

```
var fontCollection = new FontCollection();
if (!fontCollection.TryFind("arial", out FontFamily fontFamily)){
fontFamily = fontCollection.Install("/fonts/arial.ttf");
}
```

**Comment by dlemstra** [comment]
![afbeelding](https://user-images.githubusercontent.com/10426229/44935231-25fbc700-ad70-11e8-8f5c-012dded28921.png)

Could you give us a bit more information? Why doesn't it work? What is happening?

**Comment by JimBobSquarePants** [comment]
Isn't this because arial is a windows system font?

**Comment by tocsoft** [comment]
We have a class call `SystemFontCollection` that will contain all the installed system fonts we could find using the standard OS install locations.

just use fonts retrieved from `SystemFontCollection` to access the global system fonts.
