### ISSUE TITLE
GlyphMetrics - width, leaftBearing, rightBearing ? 

### ISSUE THREAD

**Issue by ststeiger** [SixLabors/Fonts#86]
I'm having a mental crisis looking at SixLabors.Fonts...
I need to replace the pinvokes for GetCharABCWidthsFloat and GetCharABCWidthsFloat. 
(for work with PDF and TIFF)

Now I thought I could do 
`font.GetGlyph('c').LeftBearing/RightBearing/Width`

Instead of properties or fields, it just has a method BoundingBox, which requires a location... 
Now of course I could pass location (0,0) but what's the point ? 
The width/height of a glyph doesn't depend on its location. 
And where's LeftBearing(A)/RightBearing(C)/B(lack) ? 
I suppose font.GetGlyph('c').BoundingBox( (0,0), dpi ).Width is =  A + B + C ? 

And then glyph takes a character as argument, makes it an integer, and then makes a character from the codepoint again ? What about VB.NET users where char is not convertible into codepoint ? Makes little sense. 

Also, I saw a leftBearing inside horizontalMetricsTable, but it's not accessible, and then there's no rightBearing ? 

Looking at QFontMetrics->inFont 
https://doc.qt.io/archives/qt-4.8/qfontmetrics.html
there's also no way to determine if a glyph is in the font ? 
What happens if it isn't in the font ? 

```
[System.Runtime.InteropServices.DllImport("GDI32", SetLastError = true)]
internal static extern int GetCharABCWidthsFloat(System.IntPtr hdc, uint iFirstChar, uint iLastChar, [System.Runtime.InteropServices.In] [System.Runtime.InteropServices.Out] ABCFloat[] lpABCF);

[System.Runtime.InteropServices.DllImport("GDI32", SetLastError = true)]
internal static extern int GetCharABCWidthsFloat(Win32DCSafeHandle hdc, uint iFirstChar, uint iLastChar, [System.Runtime.InteropServices.In] [System.Runtime.InteropServices.Out] ABCFloat[] lpABCF);
```

**Comment by ststeiger** [comment]
And another question:
why does font.GetGlyph('c'); give me BoundingBox, while font.FontInstance.GetGlyph('c')
Isn't font already an instance ? 
Why font.FontInstance ? 
And if font has FontInstance, why does Glyph not have GlyphInstance ? 
Takes only appx 3 hours of dwelling in the source code...

```
var fg = font.FontInstance.GetGlyph('c');
ushort AplusBplusC = fg.AdvanceWidth;
// fg.Index
// fg.Height
```

**Comment by JimBobSquarePants** [comment]
@ststeiger It's been a long time since this issue was raised and I've decided to look past the bitter taste I got in my mouth from reading your unpleasant tone for the greater good of others.

I've started working on clearing up the API and adding missing metrics in #187 

You'll be able to query a full set of metrics once I have completed the work and subsequent updates.

**Comment by ststeiger** [comment]
@JimBobSquarePants: Sorry for the unpleasant tone, I know this is a spare-time-project, and you put great effort into it. 

It's just that ... when it comes to font and imaging, all APIs, ms or not, fall short of everything ...
System.Drawing.Font can enumerate the fonts, but doesn't expose the file path. 
SixLabors.Fonts doesn't read fontconfig, but can read a font given the file path. Yupii.
System.Drawing can read and write gifs on Windows, but it doesn't work on Linux. 
Windows-APIs like GetCharABCWidthsFloat and fontmetrics don't document where they get the data from, you can find hints in the source-code of wine (if there isn't a E_NOT_IMPLEMENTED). 
Neither SixLabors.Fonts nor System.Drawing.Fonts can create a font-package (for embedding fonts in PDFs, but only the glyphs used to save space). 
SixLabors.Fonts reads the font-metrics-data in question, but doesn't in any way expose it (well...). 
FreeType with C# binding has a f*ing native dependency that would require typedef in C#, unless you wanna patch the windows-executable, which is a pain-in-the-a** to compile. 

And there I sit and want to replace some WinAPI calls to get PDF-rendering working on Linux, render a svg-text to a path, and write some text on a moving gif, but I can't do any of these things because I first need to read the true-type-font-specification, then dig trough the freetype documentation to understand what the values are, then read to Wine-Source-Code to figure out how to get the license-info of a ttf-file, then open issues with Microsoft for libgdiplus only to have them close it as "won't fix". 
Then dig through the sixlabors source-code to figure out how to get the metrics I need. Read through wine-code again to figure out what microsoft adds, never mind the why. Then put it all on shelf because it takes too long. 

Then take some source code a year later when you have some time again and try to get on, half the APIs of sixlabors have changed, google around for a few hours to get the things I had working working again, and, and, and ...

Then write an issue here, and then, when you still haven't done any of the stuff you wanted to do; only to here and there have people complain about how the issues I write are not written in a friendly fashion/tone, even when I have already self-censored an unhealthy amount of expletives - you would get cranky, too. 
Not that it necessarely is okay to vent all of it here. My apologies for that. 
By the way, if you ever want to render a text to a SVG-path: https://github.com/ststeiger/SvgRenderer

**Comment by JimBobSquarePants** [comment]
@ststeiger Thanks for the apology and the explanation. I appreciate it. 

Let's get back on the right foot and see what we can do to make the best possible library in our ecosystem.

Anyway.... I've made some serious progress on the metrics front. (_More API churn, sorry, but once we hit RC this stuff gets super solid._)

Here's some unit tests demonstrating the new API. We now read horizontal and vertical font metrics and return the correct EM based values for most of the useful properties. We also return comprehensive information about the `CodePoint` represented by each glyph.

It's been a LOT of work figuring out all this stuff and I've found it incredibly tricky finding decent means to compare values against existing libraries. Most of the .NET ones are incomplete or buggy and I find FreeType very difficult to navigate.

`FontMetrics`

```c#
[Fact]
public void FontMetricsMatchesReference()
{
    // Compared to FontForge metrics
    var collection = new FontCollection();
    FontFamily family = collection.Install(TestFonts.OpenSansFile);
    Font font = family.CreateFont(12);

    Assert.Equal(2048, font.FontMetrics.UnitsPerEm);
    Assert.Equal(2189, font.FontMetrics.Ascender);
    Assert.Equal(-600, font.FontMetrics.Descender);
    Assert.Equal(0, font.FontMetrics.LineGap);
    Assert.Equal(2789, font.FontMetrics.LineHeight);
    Assert.Equal(2476, font.FontMetrics.AdvanceWidthMax);
    Assert.Equal(font.FontMetrics.LineHeight, font.FontMetrics.AdvanceHeightMax);
}
``` 

`GlyphMetrics`

```c#
[Fact]
public void GlyphMetricsMatchesReference()
{
    // Compared to FontForge metrics
    var collection = new FontCollection();
    FontFamily family = collection.Install(TestFonts.OpenSansFile);
    Font font = family.CreateFont(12);

    var codePoint = new CodePoint('A');
    GlyphMetrics glyphMetrics = font.FontMetrics.GetGlyphMetrics(codePoint);
    GlyphMetrics glyphMetrics1 = font.GetGlyph(codePoint).GlyphMetrics;

    Assert.Equal(glyphMetrics, glyphMetrics1);

    Assert.Equal(codePoint, glyphMetrics.Codepoint);
    Assert.Equal(font.FontMetrics.UnitsPerEm, glyphMetrics.UnitsPerEm);
    Assert.Equal(glyphMetrics.UnitsPerEm * 72F, glyphMetrics.ScaleFactor);
    Assert.Equal(1296, glyphMetrics.AdvanceWidth);
    Assert.Equal(2789, glyphMetrics.AdvanceHeight);
    Assert.Equal(1296, glyphMetrics.Width);
    Assert.Equal(1468, glyphMetrics.Height);
    Assert.Equal(0, glyphMetrics.LeftSideBearing);
    Assert.Equal(0, glyphMetrics.TopSideBearing);
    Assert.Equal(GlyphType.Standard, glyphMetrics.GlyphType);
}
```

Regarding your comment on font paths. I've read https://github.com/dotnet/runtime/issues/49065 and while I can't deliver the `CreateFontPackage` APIs I'm wondering whether a `GetFontStream()` in the same manner as the System.Windows.Media method be useful?

**Comment by ststeiger** [comment]
> It's been a LOT of work figuring out all this stuff and I've found it incredibly tricky finding decent means to compare values against existing libraries. Most of the .NET ones are incomplete or buggy and I find FreeType very difficult to navigate.

Yea, me too, I know more abouts fonts now than I ever wanted to know, so I sympathize :) 
So I see you've been doing more of the same thing. 

By the way, I read your tweet about ShowTTF, ttfdump is available online [here](https://everythingfonts.com/ttfdump). 
Also, I don't know if I have sent a pull-request, but: 

```
 public bool IsTrueTypeFont
        {
            get
            {
                return this.OS2Table != null;
            }
        }


        public TrueTypeEmbeddability TrueTypeEmbeddingType
        {
            get
            {
                int otmfsType = (this.OS2Table.fsType & 0xf);

                if (!this.IsTrueTypeFont)
                {
                    // We could throw, or we could just define a new enum-member. 
                    // throw new System.InvalidOperationException("Not a TrueType-font.");
                    return TrueTypeEmbeddability.EMBED_NOTTRUETYPE;
                }

                if (otmfsType == (int)LicenseFlags.LICENSE_INSTALLABLE)
                    return TrueTypeEmbeddability.EMBED_INSTALLABLE;
                else if ((otmfsType & (int)LicenseFlags.LICENSE_EDITABLE) != 0)
                    return TrueTypeEmbeddability.EMBED_EDITABLE;
                else if ((otmfsType & (int)LicenseFlags.LICENSE_PREVIEWPRINT) != 0)
                    return TrueTypeEmbeddability.EMBED_PREVIEWPRINT;
                else if ((otmfsType & (int)LicenseFlags.LICENSE_NOEMBEDDING) != 0)
                    return TrueTypeEmbeddability.EMBED_NOEMBEDDING;

                // WARN("unrecognized flags, %#x\n", otmfsType);
                return TrueTypeEmbeddability.EMBED_INSTALLABLE;
            } // End Function TTGetEmbeddingType 
        }

```

https://github.com/ststeiger/SvgRenderer/blob/master/Typography.OpenFont/LicenseFlags.cs
https://github.com/ststeiger/SvgRenderer/blob/master/Typography.OpenFont/TrueTypeEmbeddability.cs

**Comment by JimBobSquarePants** [comment]
>How is GetFontStream supposed to work ?
If I have the font's path, it's no problem getting the font as stream.
If I don't have the fonts path, how would this work ?

The difficulty currently is that we haven't got a way to cleanly expose our [`FileFontMetrics`](https://github.com/SixLabors/Fonts/blob/c570014fc42ca504ecc2655a19aaca031403f433/src/SixLabors.Fonts/FileFontMetrics.cs) type so I was trying to think of a workaround. That type actually has the `Path` property you need so I'll have to figure that out as it would be much better.

>On thing
`var codePoint = new CodePoint('A');`
Why ?
Is there a deeper reason ?

That's a good question and yes, there is a deeper reason. To quote from the Microsoft docs for [`Rune`](https://docs.microsoft.com/en-us/dotnet/api/system.text.rune?view=net-5.0#when-to-use-the-rune-type). If your code iterates through the `char` instances in a `string` or a `ReadOnlySpan<char>`, some of the `char` methods won't work correctly on `char` instances that are in the surrogate range. 

For example, the following APIs require a scalar value char to work correctly:

- Char.GetNumericValue
- Char.GetUnicodeCategory
- Char.IsDigit
- Char.IsLetter
- Char.IsLetterOrDigit
- Char.IsLower
- Char.IsNumber
- Char.IsPunctuation
- Char.IsSymbol
- Char.IsUpper

In the design of the API I wanted to do two things: 

1. Enforce safe enumeration of string and capture any issues at the highest level. 
2. Ensure that the correct information was gathered and returned for each codepoint in the text input so that you can make decisions regarding text layout (_if you're not using ours, which works well but has limitations_)

A missing piece of the API puzzle which allows you to effectively enumerate strings for codepoints and pass those directly to our methods will be provided by #189  

With that you will be able to do things like the following:

``` c#
[Fact]
public void CanEnumerateReadonlySpan()
{
    // Test example taken from.
    // https://docs.microsoft.com/en-us/dotnet/api/system.text.rune?view=net-5.0#when-to-use-the-rune-type
    const string text = "𐓏𐓘𐓻𐓘𐓻𐓟 𐒻𐓟";
    int letterCount = 0;

    foreach (CodePoint codePoint in text.AsSpan().EnumerateCodePoints())
    {
        if (CodePoint.IsLetter(codePoint))
        {
            letterCount++;
        }
    }

    Assert.Equal(8, letterCount);
}
```

You can also construct the `SpanCodePointEnumerator` struct directly.

**Comment by JimBobSquarePants** [comment]
@ststeiger This might interest you... 😉
https://github.com/SixLabors/Fonts/pull/190

**Comment by JimBobSquarePants** [comment]
I think we’ve covered all the metrics properties now so I’m going to close this. If I’ve missed something please let me know and open a new issue!
