### ISSUE TITLE
Glyph Functionality Questions

### ISSUE THREAD

**Issue by Cryru** [SixLabors/Fonts#89]
I have a few questions which should probably be turned into documentation and samples down the line as currently, they aren't very clear (at least to me - quite possible I missed it).

How would one go about getting the metrics of a single glyph within a font? The Font class' `GetGlyph` function is internal, and it returns an object which doesn't have them (which would be GlyphInstance, I guess?).

There is a sample showing how to render text, but how do you render a single glyph? I would like to render the glyphs to an atlas and then render that using something else.

**Comment by wchill** [comment]
I'm curious about this too - I'm looking to render text that may be in multiple languages, so I need to be able to detect when a font does not have a glyph for a given codepoint.

**Comment by Jjagg** [comment]
@Cyru This is briefly addressed in #77.

**Comment by feliwir** [comment]
Trying this aswell
