### ISSUE TITLE
superscript

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Fonts#9]
render portions of text in a superscript style

**Comment by JimBobSquarePants** [comment]
Fairly certain this will be covered by the GPOS support provided by https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#lookup-type-1-single-adjustment-positioning-subtable

**Comment by JimBobSquarePants** [comment]
While the support exists via #198 the [feature tag](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-sups) is not enabled by default as per spec recommendation. We need to plan to allow this.

**Comment by JimBobSquarePants** [comment]
Fixed with #248 and #251
