### ISSUE TITLE
中文逗号显示不正确

### ISSUE THREAD

**Issue by 497721822** [SixLabors/Fonts#92]
图片加入文字的时候，中文的逗号"，"会被改成“-”，麻烦更正一下，谢谢。
![qq 20181116113112](https://user-images.githubusercontent.com/13652802/48596248-2aa94200-e993-11e8-89a1-46ae7305e874.png)

**Comment by 497721822** [comment]
I will submit another issue and translate this probram.Thank you.

**Comment by 497721822** [comment]
> Our team cannot read or write Chinese. What are you asking us?

I will submit another issue and translate this probram.Thank you.

**Comment by JimBobSquarePants** [comment]
Closed. Replaced by #93
