### ISSUE TITLE
Some punctuation cannot be output to the image

### ISSUE THREAD

**Issue by 497721822** [SixLabors/Fonts#93]
I get a probram when i use this sdk  package.
I try to input some punctuation,but it con not output to the image.Now,i list all problematic punctuation,and i hope you can help solve this problem.
The problematic punctuation is " ，；：！￥（）？｛｝－＝＋＼｜～！＠＃％＆． "。
Thank you.

**Comment by prepare** [comment]
Can you provide that font?

**Comment by microchi** [comment]
@prepare 
You can download the Chinese fonts from Microsoft website. 
And then unzip the EXE file to get fonts.
[Traditional Chinese ClearType fonts](http://www.microsoft.com/en-us/download/details.aspx?id=12072)
[Simplified Chinese ClearType fonts](http://www.microsoft.com/en-us/download/details.aspx?id=14577)

**Comment by JimBobSquarePants** [comment]
Just had a look at this with the latest beta. 

Using Microsoft JhengHei this appears to render perfectly. As such I'm closing the issue as fixed.

![ ，；：！￥（）？｛｝－＝＋＼｜～！＠＃％＆](https://user-images.githubusercontent.com/385879/125163937-76820880-e187-11eb-9173-392102a9ca90.png)
